/**
 * UN ICONO POR COMANDO. Catálogo propio, y por eso existe este archivo.
 *
 * ## Qué había, y qué se midió
 *
 * `ribbon-icons.ts` reparte un icono por PANEL: los veintiséis comandos de
 * «Modificar» salían los veintiséis con la misma llave inglesa. Era honesto
 * —no inventaba una distinción que la cinta no hacía— y era exactamente lo que
 * `docs/competitive/distancia-autocad-completo-20260903.md` cuenta entre los
 * tres reflejos caros que quedaban abiertos: **0 iconos por comando**. En
 * AutoCAD la cinta se lee por la FORMA del botón, no por su texto; una cinta de
 * iconos repetidos obliga a leer 247 rótulos.
 *
 * ## De dónde salen los dibujos
 *
 * De **lucide** (ISC, ya en el árbol de dependencias y ya declarado en
 * `THIRD_PARTY_NOTICES.md`). No hay ni un trazo de iconografía de Autodesk aquí
 * ni en ningún otro sitio del producto: eso no es una precaución, es la regla
 * de procedencia de la campaña. Lo que este archivo aporta es la ASIGNACIÓN
 * —qué dibujo le toca a cada orden—, que es trabajo propio y se lee como tal.
 *
 * ## Por qué la tabla es explícita y no un algoritmo
 *
 * Se probaron reglas por prefijo (`LAY*`, `DIM*`, `GC*`) y producen justo el
 * problema que venimos a quitar: trece restricciones geométricas idénticas. Lo
 * que un dibujante reconoce es que PARALELA no se parece a PERPENDICULAR, y eso
 * no lo deduce ningún prefijo. La tabla es larga a propósito.
 *
 * ## El contrato
 *
 * `command-icons.spec.ts` recorre el registro REAL y falla si un comando no
 * tiene icono. Un comando nuevo no puede entrar mudo en la cinta — la misma
 * regla que ya tienen los resúmenes de la paleta.
 */
import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  Anchor,
  AppWindow,
  ArrowDownUp,
  ArrowLeftRight,
  Axe,
  Axis3d,
  BadgeCheck,
  Ban,
  Baseline,
  Blend,
  Blinds,
  Bolt,
  Box,
  Blocks,
  Boxes,
  Braces,
  Cable,
  ListChecks,
  CaseSensitive,
  Circle,
  CircleDashed,
  CircleDot,
  CircleDotDashed,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ListTree,
  Factory,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardPen,
  Cog,
  Columns2,
  Columns3,
  Combine,
  Compass,
  Cone,
  Copy,
  CopyPlus,
  CornerDownRight,
  CornerUpRight,
  Crop,
  Cylinder,
  DoorOpen,
  Download,
  Droplets,
  Egg,
  Equal,
  Eraser,
  Eye,
  EyeOff,
  Fence,
  FileCode,
  FileCog,
  FileInput,
  FileOutput,
  FileText,
  Files,
  Filter,
  FlaskConical,
  FlipHorizontal2,
  FlipVertical2,
  Focus,
  FolderOpen,
  Footprints,
  Fullscreen,
  Globe,
  Grid2x2,
  Grid3x3,
  Group,
  Hammer,
  Hand,
  Hash,
  Hexagon,
  History,
  House,
  Image,
  ImagePlus,
  Layers,
  Layers2,
  LayoutGrid,
  LayoutPanelTop,
  Link,
  Link2,
  List,
  ListOrdered,
  Locate,
  Magnet,
  Map,
  MapPin,
  Maximize,
  Merge,
  Microscope,
  Milestone,
  Minus,
  MousePointerClick,
  Move,
  MoveDiagonal,
  MoveHorizontal,
  MoveVertical,
  Network,
  Orbit,
  PaintBucket,
  Palette,
  PanelTop,
  PenLine,
  PenTool,
  Check,
  PencilRuler,
  Pentagon,
  Percent,
  Pin,
  Pipette,
  Plug,
  Printer,
  Proportions,
  Puzzle,
  Pyramid,
  Ratio,
  RectangleHorizontal,
  Redo2,
  RefreshCcw,
  Repeat,
  Repeat2,
  Rotate3d,
  RotateCcw,
  RotateCw,
  Route,
  Rows3,
  Ruler,
  Save,
  Scaling,
  Scan,
  ScanLine,
  Scissors,
  Search,
  Send,
  Settings2,
  Shapes,
  ShieldCheck,
  Signpost,
  Slash,
  Slice,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Spline,
  Split,
  Spool,
  SquareStack,
  Square,
  SquareDashed,
  SquareDashedMousePointer,
  SquareDot,
  SquareFunction,
  StretchHorizontal,
  Sun,
  Table,
  Table2,
  TableCellsMerge,
  TableProperties,
  Tag,
  Tags,
  Terminal,
  Trash2,
  Triangle,
  TriangleAlert,
  Type,
  TypeOutline,
  Undo2,
  Ungroup,
  Unlink,
  Upload,
  View,
  Waves,
  Waypoints,
  Weight,
  Wind,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

/** Nombre canónico del comando → su dibujo. Fail-closed: no hay reposo. */
export const CAD_COMMAND_ICONS: Readonly<Record<string, LucideIcon>> = {
  LINE: Minus,
  PLINE: Spline,
  CIRCLE: Circle,
  ARC: CircleDashed,
  RECTANG: RectangleHorizontal,
  POLYGON: Hexagon,
  ELLIPSE: Egg,
  SPLINE: Waves,
  XLINE: Slash,
  RAY: CornerUpRight,
  POINT: CircleDot,
  DIVIDE: Columns3,
  MEASURE: Ruler,
  DONUT: CircleDotDashed,
  REGION: SquareDot,
  SOLID: Triangle,
  REVCLOUD: Sparkles,
  WIPEOUT: Eraser,
  BOUNDARY: SquareDashed,
  HATCH: PaintBucket,
  GRADIENT: Blend,
  U: Undo2,
  UNDO: History,
  REDO: Redo2,
  MOVE: Move,
  COPY: Copy,
  ROTATE: RotateCw,
  SCALE: Scaling,
  MIRROR: FlipHorizontal2,
  OFFSET: Layers2,
  TRIM: Scissors,
  EXTEND: MoveHorizontal,
  FILLET: CornerDownRight,
  CHAMFER: Pentagon,
  ARRAY: Grid2x2,
  STRETCH: StretchHorizontal,
  ERASE: Trash2,
  EXPLODE: Split,
  BREAK: Slice,
  JOIN: Merge,
  LENGTHEN: ArrowLeftRight,
  PEDIT: PenTool,
  ALIGN: AlignLeft,
  BLEND: Waypoints,
  DRAWORDER: Layers,
  ARRAYEDIT: Grid3x3,
  NCOPY: CopyPlus,
  OVERKILL: Combine,
  SPLINEDIT: Spool,
  XPLODE: Shapes,
  LAYER: Layers,
  "-LAYER": Terminal,
  LAYISO: Focus,
  LAYUNISO: Fullscreen,
  LAYOFF: EyeOff,
  LAYON: Eye,
  LAYFRZ: Snowflake,
  LAYTHW: Sun,
  LAYMCH: Pipette,
  LAYWALK: Footprints,
  LAYERSTATE: Save,
  LAYMRG: Merge,
  VPLAYER: PanelTop,
  LAYTRANS: ArrowDownUp,
  INSERT: Puzzle,
  BLOCK: Boxes,
  BEDIT: FileCog,
  WBLOCK: FolderOpen,
  ATTDEF: Tag,
  ATTEDIT: Tags,
  // Sincronizar no es editar: el dibujo del ciclo lo dice antes que el rótulo.
  ATTSYNC: RefreshCcw,
  BURST: Sparkles,
  BASE: Anchor,
  ADCENTER: FolderOpen,
  XATTACH: Link,
  XREF: Link2,
  XBIND: Unlink,
  XCLIP: Crop,
  IMAGE: Image,
  IMAGEATTACH: ImagePlus,
  IMAGECLIP: Crop,
  IMAGEADJUST: SlidersHorizontal,
  PROPERTIES: SlidersHorizontal,
  MATCHPROP: Pipette,
  COLOR: Palette,
  LINETYPE: Minus,
  LWEIGHT: Weight,
  LTSCALE: Ratio,
  CELTSCALE: Percent,
  "-LINETYPE": Terminal,
  CHPROP: Settings2,
  SETBYLAYER: Layers2,
  GROUP: Group,
  UNGROUP: Ungroup,
  QSELECT: Filter,
  FILTER: Search,
  ADDSELECTED: MousePointerClick,
  SELECTSIMILAR: SquareDashedMousePointer,
  DIST: Ruler,
  AREA: Proportions,
  ID: MapPin,
  LIST: List,
  MASSPROP: Weight,
  PASTECLIP: ClipboardPaste,
  CUTCLIP: Scissors,
  COPYCLIP: ClipboardCopy,
  COPYBASE: Clipboard,
  PASTEORIG: ClipboardPen,
  WALL: Fence,
  DOOR: DoorOpen,
  WINDOW: Blinds,
  STAIR: Rows3,
  ROOF: House,
  SLAB: Square,
  PIPE: Droplets,
  DUCT: Wind,
  CABLETRAY: Cable,
  MEPSYMBOL: Plug,
  AEWIRE: Cable,
  AEWIRELIST: ListChecks,
  AECIRCUIT: Zap,
  AECHECK: ShieldCheck,
  AETAG: Tag,
  AETAGLIST: Tags,
  PIDLINE: Waypoints,
  PIDLIST: ClipboardList,
  PIDEQUIP: Factory,
  PIDEQUIPLIST: ListTree,
  PIDROUTE: Spline,
  PIDMTO: ClipboardCheck,
  PIDISO: Boxes,
  BLOQUEDIN: Blocks,
  BLOQUEDINSET: SlidersHorizontal,
  BLOQUEDINLIST: ListTree,
  BLOQUEDINDEF: Ruler,
  REFEDIT: PencilRuler,
  REFSET: SquareStack,
  REFCLOSE: Check,
  BOX: Box,
  CYLINDER: Cylinder,
  CONE: Cone,
  SPHERE: Circle,
  WEDGE: Triangle,
  TORUS: CircleDotDashed,
  PYRAMID: Pyramid,
  POLYSOLID: Fence,
  EXTRUDE: MoveVertical,
  REVOLVE: RotateCcw,
  SWEEP: Route,
  LOFT: Layers,
  PRESSPULL: MoveDiagonal,
  UNION: Combine,
  SUBTRACT: Ban,
  INTERSECT: Blend,
  SOLIDEDIT: Hammer,
  FILLETEDGE: CornerDownRight,
  CHAMFEREDGE: Pentagon,
  SLICE: Slice,
  SECTION: Axe,
  INTERFERE: TriangleAlert,
  FLATSHOT: ScanLine,
  SOLVIEW: LayoutGrid,
  SOLDRAW: PenLine,
  SOLPROF: Scan,
  PAN: Hand,
  ZOOM: ZoomIn,
  "3DORBIT": Orbit,
  "3DFORBIT": Rotate3d,
  "3DPAN": Hand,
  "3DZOOM": ZoomOut,
  PLAN: Map,
  VIEW: View,
  VPOINT: Compass,
  VSCURRENT: Sun,
  REGEN: Repeat,
  REGENALL: Repeat2,
  UCS: Axis3d,
  UCSICON: Locate,
  UCSMAN: Compass,
  "-UCSMAN": Terminal,
  MSPACE: Maximize,
  PSPACE: FileText,
  MVIEW: AppWindow,
  LAYOUT: Files,
  PAGESETUP: FileCog,
  PLOT: Printer,
  PUBLISH: Send,
  SHEETSET: Files,
  ETRANSMIT: Upload,
  DXFOUT: FileOutput,
  DXFIN: FileInput,
  EXPORT: Download,
  IMPORT: Upload,
  DATAEXTRACTION: Table2,
  TEXT: Type,
  MTEXT: TypeOutline,
  DDEDIT: CaseSensitive,
  TEXTALIGN: AlignCenter,
  TABLE: Table,
  TABLEDIT: TableProperties,
  TABLESTYLE: TableCellsMerge,
  STYLE: Baseline,
  // Las plumas del trazado: el dibujo de la pluma, no el del papel.
  STYLESMANAGER: PenTool,
  DIMLINEAR: Ruler,
  DIMALIGNED: PencilRuler,
  DIMANGULAR: Triangle,
  DIMRADIUS: CircleDashed,
  DIMDIAMETER: CircleDot,
  DIMARC: Spline,
  DIMORDINATE: Axis3d,
  DIMCONTINUE: ArrowLeftRight,
  DIMBASELINE: AlignJustify,
  QDIM: Zap,
  DIM: Ruler,
  DIMEDIT: PenLine,
  DIMSTYLE: Settings2,
  DIMTOLERANCE: Percent,
  LEADER: CornerUpRight,
  MLEADER: Milestone,
  QLEADER: Signpost,
  MLEADERSTYLE: Settings2,
  TOLERANCE: BadgeCheck,
  BALLOON: CircleDot,
  BOM: ListOrdered,
  WELDSYMBOL: Triangle,
  SURFACESYMBOL: ScanLine,
  STDPART: Bolt,
  STEELSHAPE: Columns2,
  GEOGRAPHICLOCATION: Globe,
  MAPIMPORT: Map,
  AUTOCONSTRAIN: Magnet,
  GEOMCONSTRAINT: Network,
  GCCOINCIDENT: CircleDot,
  GCCOLLINEAR: Minus,
  GCCONCENTRIC: CircleDotDashed,
  GCFIX: Pin,
  GCPARALLEL: Equal,
  GCPERPENDICULAR: CornerDownRight,
  GCHORIZONTAL: MoveHorizontal,
  GCVERTICAL: MoveVertical,
  GCTANGENT: Circle,
  GCSMOOTH: Waves,
  GCSYMMETRIC: FlipVertical2,
  GCEQUAL: Equal,
  DCLINEAR: Ruler,
  DCANGULAR: Triangle,
  DCRADIUS: CircleDashed,
  DCDIAMETER: CircleDot,
  DIMCONSTRAINT: Magnet,
  DELCONSTRAINT: Unlink,
  PARAMETERS: SquareFunction,
  AUDIT: Microscope,
  RECOVER: FlaskConical,
  PURGE: Trash2,
  RENAME: CaseSensitive,
  CHECKSTANDARDS: ShieldCheck,
  NORMAMX: BadgeCheck,
  UNITS: Ratio,
  OPTIONS: Cog,
  SETVAR: Braces,
  GETVAR: Hash,
  DSETTINGS: Grid3x3,
  "-DSETTINGS": Terminal,
  OSNAP: Magnet,
  "-OSNAP": Terminal,
  TOOLPALETTES: LayoutPanelTop,
  "-TOOLPALETTES": Terminal,
  SCRIPT: FileCode,
  RSCRIPT: Repeat,
};

/**
 * El icono de un comando. Sin reposo a propósito: quien pregunte por uno que no
 * está recibe `null` y quien pinta decide qué hacer, en vez de dibujar un
 * genérico que oculta el hueco. El gate lo convierte en imposible.
 */
export function cadCommandIcon(command: string): LucideIcon | null {
  return CAD_COMMAND_ICONS[command.toUpperCase()] ?? null;
}
