/**
 * Rótulos cortos en español de los comandos del motor — el texto del BOTÓN de
 * la cinta.
 *
 * ## Por qué existe este archivo
 *
 * El botón de la cinta pintaba el nombre canónico en inglés (LINE, RECTANG,
 * MATCHPROP). En AutoCAD es-MX el botón dice «Línea», «Rectángulo», «Igualar
 * formato», y el nombre con su alias vive en el tooltip. El resumen
 * (`command-summaries.ts`) es una frase; aquí va lo que cabe en un botón:
 * una o dos palabras, tres como mucho.
 *
 * ## El contrato es FAIL-CLOSED, igual que el de los resúmenes
 *
 * Todo comando del registro tiene rótulo y ningún rótulo nombra un comando
 * que ya no existe (`command-labels.spec.ts`). `cadCommandLabel` lanza en
 * vez de devolver una cadena vacía: un botón mudo no es una opción.
 *
 * ## Qué dice cada rótulo
 *
 * Lo que el comando HACE en este producto, no lo que promete el nombre:
 * PLOT traza a PDF y por eso dice «Trazar a PDF»; los comandos con guion
 * («-LAYER») trabajan por la línea de comandos y lo dicen entre paréntesis.
 * Los botones pequeños de la cinta miden 7 rem (`w-28`, `CadRibbonButton.tsx`):
 * tras el icono y el hueco, el rótulo tiene 88 px hasta el borde del botón, y
 * el golden 214 falla si lo pasa. 16 caracteres es sólo la cota gruesa que
 * comprueba `command-labels.spec.ts`: el Chromium de Linux del CI pinta Inter
 * 500 a 11 px hasta un 5 % más ancho que el de Windows, y «Adjuntar imagen»
 * (15), que en Windows mide 87 px, allí midió ~90 y tumbó el golden. Un
 * rótulo pequeño a la vista a 1366 o 1280 px no pasa de 83 px medido en
 * Windows. Los primarios se pintan grandes, con el rótulo en dos líneas, y
 * ahí lo que manda es que ninguna palabra pase de 12 caracteres.
 */

/** Nombre canónico → rótulo del botón. Orden alfabético, como el registro. */
export const CAD_COMMAND_LABELS: Readonly<Record<string, string>> = {
  "-DSETTINGS": "Ayudas cl",
  "-LAYER": "Capas (línea)",
  "-LINETYPE": "Tipos (línea)",
  "-OSNAP": "Refent cl",
  "-TOOLPALETTES": "Paletas cl",
  "-UCSMAN": "Gestor cl",


  "3DFACE": "Cara 3D",
  "3DFLY": "Volar 3D",
  "3DFORBIT": "Libre",
  "3DMOVE": "Mover 3D",
  "3DARRAY": "Arreglo 3D",
  "3DORBIT": "Órbita 3D",
  "3DPAN": "Encu. 3D",
  "3DROTATE": "Rotar 3D",
  "3DSCALE": "Escalar 3D",
  "3DALIGN": "Alinear 3D",

  "3DSWIVEL": "Girar vista",
  "3DWALK": "Caminar 3D",
  "3DZOOM": "Zoom 3D",
  ABOUT: "Acerca",
  ACTMANAGER: "Macros",
  ACTRECORD: "Grabar",
  ACTSTOP: "Parar",
  ADCENTER: "DesignCenter",
  ADDSELECTED: "Dibujar igual",
  AECHECK: "Rev NOM",
  AECIRCUIT: "Circuito",
  AESYMBOL: "Eléctrico",
  AETAG: "Etiquetar",
  AETAGLIST: "Etiquetas",
  AEWIRE: "Cable",
  AEWIRELIST: "Cables",
  ALIGN: "Alinear",
  ARC: "Arco",
  AREA: "Área",
  ARRAY: "Matriz",
  ARRAYEDIT: "Editar matriz",
  ATTDEF: "Definir atributo",
  ATTEDIT: "Editar atributo",
  ATTSYNC: "Sincronizar",
  AUDIT: "Auditar",
  AUTOCONSTRAIN: "Automáticas",
  BALLOON: "Globo",
  BASE: "Punto base",
  BEDIT: "Editar bloque",
  BLEND: "Fusionar curvas",
  BLOCK: "Crear bloque",
  BLOQUEDIN: "Bloque dinámico",
  BLOQUEDINDEF: "Hacer dinámico",
  BLOQUEDINLIST: "Listar dinámicos",
  BLOQUEDINSET: "Fijar parámetro",
  BOM: "Piezas",
  BOUNDARY: "Contorno",
  BOX: "Caja",
  BREAK: "Partir",
  BREAKATPOINT: "Partir punto",
  BREAKLINE: "Línea de rotura",
  BURST: "Estallar",
  CABLETRAY: "Charola",
  CAMERA: "Cámara",

  CELTSCALE: "Escala objeto",
  CENTERLINE: "Eje",
  CENTERMARK: "Marca de centro",
  CHAMFER: "Chaflán",
  CHAMFEREDGE: "Chafl 3D",
  CHECKSTANDARDS: "Normas",
  CHPROP: "Cambiar (línea)",
  CIRCLE: "Círculo",
  COGO: "Poligonal",
  COLOR: "Color",
  COMPARE: "Comparar",
  CONE: "Cono",
  CONVTOMESH: "A malla",
  CONVTOSOLID: "A sólido",
  CONVTOSURFACE: "A sup.",
  COPY: "Copiar",
  COPYBASE: "Copiar con base",
  COPYCLIP: "Copiar Ctrl+C",
  CUADROCONSTRUCCION: "Cuadro",
  CUTCLIP: "Cortar Ctrl+X",
  CYLINDER: "Cilindro",
  DATAEXTRACTION: "Cómputo",
  DCANGULAR: "Angular",
  DCDIAMETER: "Diámetro",
  DCLINEAR: "Lineal",
  DCRADIUS: "Radio",
  DDEDIT: "Ed. texto",
  DELCONSTRAINT: "Eliminar",
  DIM: "Acotar",
  DIMALIGNED: "Alineada",
  DIMANGULAR: "Angular",
  DIMARC: "L. arco",
  DIMBASELINE: "Base",
  DIMCONSTRAINT: "Convertir",
  DIMCONTINUE: "Continuar",
  DIMDIAMETER: "Diámetro",
  DIMEDIT: "Editar",
  DIMLINEAR: "Lineal",
  DIMORDINATE: "Ordenada",
  DIMRADIUS: "Radio",
  DIMSTYLE: "Estilo de cota",
  DIMTOLERANCE: "Tolerancia cota",
  DIST: "Distancia",
  DISTANTLIGHT: "Luz direccional",
  DIVIDE: "Dividir",
  DONUT: "Arandela",
  DOOR: "Puerta",
  DRAWORDER: "Orden de dibujo",
  DSETTINGS: "Ayudas",
  DUCT: "Ducto",
  DVIEW: "Vista dinámica",

  DXFIN: "Importar DXF",
  DXFOUT: "Exportar DXF",
  SAVEAS: "Copia",
  ELLIPSE: "Elipse",
  ERASE: "Borrar",
  ETRANSMIT: "Empaq.",
  EXPLODE: "Descomponer",
  EXPORT: "Exportar",
  EXTEND: "Alargar",
  EXTRUDE: "Extruir",
  FIELD: "Campo",
  FILLET: "Empalme",
  FILLETEDGE: "Empal 3D",
  FIND: "Buscar",
  FILL: "Relleno",
  FILTER: "Filtro",
  FLATSHOT: "Aplanar",
  FLATTEN: "Aplastar a Z=0",
  GCCOINCIDENT: "Coincide",
  GCCOLLINEAR: "Colineal",
  GCCONCENTRIC: "Concén.",
  GCEQUAL: "Igual",
  GCFIX: "Fijo",
  GCHORIZONTAL: "Horiz.",
  GCPARALLEL: "Paralelo",
  GCPERPENDICULAR: "Perpend.",
  GCSMOOTH: "Suave",
  GCSYMMETRIC: "Simétrico",
  GCTANGENT: "Tangente",
  GCVERTICAL: "Vertical",
  GEOGRAPHICLOCATION: "Geolocalizar",
  GEOMCONSTRAINT: "Restricción",
  GETVAR: "Leer var.",
  GRADIENT: "Degradado",
  GROUP: "Agrupar",
  HATCH: "Sombreado",
  ID: "Coordenadas",
  IMAGE: "Imagen",
  IMAGEADJUST: "Ajus. IMG",
  IMAGEATTACH: "Adj. IMG",
  IMAGECLIP: "Cort. IMG",
  IMPORT: "Importar",
  INSERT: "Insertar",
  INTERFERE: "Interfer.",
  INTERSECT: "Intersec.",
  JOIN: "Unir",
  LAYCUR: "Capa actual",
  LAYDEL: "Borrar capa",
  LAYER: "Gestor de capas",
  LAYERSTATE: "Estados de capa",
  LAYFRZ: "Congelar",
  LAYISO: "Aislar",
  LAYMCH: "Igualar capa",
  LAYMRG: "Fusionar capa",
  LAYOFF: "Apagar",
  LAYON: "Activar todas",
  LAYOUT: "Present.",
  LAYTHW: "Descongelar",
  LAYTRANS: "Traducir",
  LAYUNISO: "Desaislar",
  LAYWALK: "Recorrer capas",
  LEADER: "Directriz",
  LENGTHEN: "Longitud",
  LINE: "Línea",
  LINETYPE: "Tipo de línea",
  LIST: "Listar",
  LOFT: "Solevar",
  LTSCALE: "Escala global",
  LWEIGHT: "Grosor de línea",
  MAPIMPORT: "GIS",
  MASSPROP: "Masa y volumen",
  // Ola 1 «cinta» (2026-09-19): dejó de ser botón grande de «Propiedades»
  // (PROPERTIES es ahora el único primario del panel) — como botón pequeño
  // el rótulo tiene que caber en 16 caracteres (`command-labels.spec.ts`);
  // «Igualar propiedades» (19) no cabía.
  MATCHPROP: "Igualar formato",
  MATERIALS: "Materiales",
  MATERIALATTACH: "Asignación",
  MATERIALMAP: "Mapeado",
  MEASURE: "Graduar",
  MESH: "Malla",

  MEPSYMBOL: "Símbolo",
  MIRROR: "Simetría",
  MIRROR3D: "Simetría 3D",

  MLEADER: "Directriz nota",
  MLEADERSTYLE: "Estilo dir.",
  MOVE: "Desplazar",
  MSPACE: "Espacio modelo",
  MTEXT: "Texto multilínea",
  MVIEW: "Ventana gráfica",

  NCOPY: "Copiar anidado",
  NORMAMX: "México",
  NAVBAR: "Navegación",
  NAVVCUBE: "Cubo 3D",
  OFFSET: "Desfase",
  OPTIONS: "Opciones",
  OSNAP: "Refent",
  OVERKILL: "Duplicados",
  PAGESETUP: "Preparar",
  PAN: "Encuadre",
  PARAMETERS: "Parámetros",
  PASTECLIP: "Pegar Ctrl+V",
  PASTEORIG: "Pegar en origen",
  PERSPECTIVE: "Perspect.",
  PDFADJUST: "Ajus. PDF",
  PDFATTACH: "Adj. PDF",
  PDFCLIP: "Cort. PDF",
  PDFDETACH: "Quit. PDF",
  PDFIMPORT: "Importar",
  PDFLIST: "List. PDF",
  PDFPAGE: "Pág. PDF",
  PDFRELOAD: "Recargar",
  PDFSCALE: "Cal. PDF",
  PDFUNLOAD: "Vac. PDF",
  PEDIT: "Editar polilínea",
  PIDEQUIP: "Equipo",
  PIDEQUIPLIST: "Equipos",
  PIDISO: "Isométrico",
  PIDLINE: "Línea proceso",
  PIDLIST: "Listar líneas",
  PIDMTO: "Materiales tubo",
  PIDROUTE: "Tubería 3D",
  PIPE: "Tubería",
  PLAN: "Planta",
  PLANESURF: "Superficie plana",
  PLINE: "Polilínea",
  PLOT: "Trazar a PDF",
  PLOTSTAMP: "Sello",
  POINT: "Punto",
  POINTLIGHT: "Luz puntual",
  POLYGON: "Polígono",
  POLYSOLID: "Polisólido",
  PRESSPULL: "Empujar",
  PROPERTIES: "Propiedades",
  PSPACE: "Papel",
  PUBLISH: "Publicar",
  PURGE: "Limpiar",
  PYRAMID: "Pirámide",
  QDIM: "Rápida",
  QLEADER: "Dir. ráp.",
  QSELECT: "Selección rápida",
  RAY: "Rayo",
  RECOVER: "Reparar",
  RECTANG: "Rectáng.",
  MREDO: "Rehacer varios",
  REDO: "Rehacer",
  REFCLOSE: "Cerrar edición",
  REFEDIT: "Editar en sitio",
  REFSET: "Conjunto edición",
  REDRAW: "Redibujar",
  REGEN: "Regenerar",
  REGENALL: "Todas",
  REGION: "Región",
  RENDER: "Renderizar",
  RENDERCROP: "Recorte render",
  RENDERENVIRONMENT: "Entorno render",
  RENDEREXPOSURE: "Exposición",
  RENDERPRESETS: "Calidad render",
  RENDERWIN: "Ventana render",
  RENAME: "Renom.",

  REVCLOUD: "Nube de revisión",
  REVERSE: "Invertir",
  REVISA: "Revisar",
  REVOLVE: "Revoluc.",
  ROOF: "Cubierta",
  ROTATE: "Girar",
  RSCRIPT: "Repetir",
  REVSURF: "Revoluc.",
  MESHSMOOTH: "Suavizar",
  MESHSMOOTHMORE: "+ suave",
  MESHSMOOTHLESS: "− suave",
  MESHREFINE: "Refinar",
  MESHCOLLAPSE: "Colapsar malla",
  MESHCAP: "Tapar",
  MESHMERGE: "Unir",
  MESHSPLIT: "Dividir",
  MESHUNCREASE: "Quitar",
  MESHCREASE: "Marcar",
  MESHEXTRUDE: "Extruir malla",
  EDGESURF: "Bordes",
  RULESURF: "Superficie reglada",
  SCALE: "Escala",
  SCRIPT: "Ejecutar guion",
  SECTION: "Sección",
  SELECTSIMILAR: "Designar similar",
  SETBYLAYER: "Poner PorCapa",
  SETVAR: "Fijar var.",
  SHEETSET: "Planos",
  SLAB: "Losa",
  SLICE: "Rebanar",
  SOLDRAW: "Generar",
  SOLID: "Sólido 2D",
  SOLIDEDIT: "Editar",
  SOLPROF: "Perfil 2D",
  SOLVIEW: "Ventanas",
  SPHERE: "Esfera",
  STATUS: "Estado",

  SPLINE: "Spline",
  SPLINEDIT: "Editar spline",
  SPOTLIGHT: "Foco",
  STAIR: "Escalera",
  STDPART: "Normalizado",
  STEELSHAPE: "Acero",
  STRETCH: "Estirar",
  STYLE: "Estilo de texto",
  STYLESMANAGER: "Plumas",
  SUBTRACT: "Restar",
  SUNPROPERTIES: "Propiedades sol",
  SURFACESYMBOL: "Acabado",
  SURFOFFSET: "Vaciar",
  SURFTRIM: "Cort. sup",
  SURFUNTRIM: "Restaurar sup",
  SURFPATCH: "Parchear sup",
  SURFNETWORK: "Red sup",
  SURFBLEND: "Mez. sup",
  SURFEXTEND: "Ext. sup",
  SURFFILLET: "Filete sup",
  SURFSCULPT: "Esculpir sup",
  SWEEP: "Barrido",
  TABLE: "Tabla",
  TABLEDIT: "Editar celda",
  TABLESTYLE: "Est. tabla",
  TABSURF: "Tabulada",
  TCOUNT: "Numerar textos",
  TEXT: "Texto",
  TEXTALIGN: "Alinear",
  TIME: "Tiempo",

  TOLERANCE: "Tolerancia",
  TOOLPALETTES: "Paletas",
  TORUS: "Toroide",
  TRIM: "Recortar",
  TXT2MTXT: "Fundir textos",
  U: "Deshacer",
  UCS: "SCU",
  UCSICON: "Icono",
  UCSMAN: "Gestor",
  UNDO: "Deshacer varios",
  UNGROUP: "Desagrupar",
  UNION: "Unión",
  UNITS: "Unidades",
  UPDATEFIELD: "Actualizar campo",
  VECTORIZE: "Calcar",
  VIEW: "Guardada",
  VIEWBASE: "Vista base",
  VIEWDETAIL: "Detalle",
  VIEWEDIT: "Editar vista",
  VIEWPROJ: "Proy.",
  VIEWSECTION: "Sección",
  VIEWUPDATE: "Actualizar vista",
  VIEWRES: "Resol.",
  VISUALSTYLES: "Estilos visuales",
  VPLAYER: "Capas en ventana",
  VPOINT: "Punto",
  VSCURRENT: "Estilo visual",
  WALL: "Muro",
  WBLOCK: "Publicar bloque",
  WEDGE: "Cuña",
  WELDSYMBOL: "Soldeo",
  WINDOW: "Ventana",
  WIPEOUT: "Máscara",
  XATTACH: "Adjuntar xref",
  XBIND: "Fijar xref",
  XCLIP: "Cort. xref",
  XLINE: "Recta",
  XPLODE: "Explotar a capa",
  XREF: "List. xref",
  ZOOM: "Zoom",
};

/** Rótulo del botón; lanza si el comando no tiene (el silencio no es opción). */
export function cadCommandLabel(name: string): string {
  const label = CAD_COMMAND_LABELS[name.toUpperCase()];
  if (!label) throw new Error(`el comando ${name.toUpperCase()} no tiene rótulo en command-labels.ts`);
  return label;
}
