/**
 * Resúmenes en español de los comandos del motor — el texto de la paleta Ctrl+K.
 *
 * ## Por qué existe este archivo
 *
 * El descriptor V2 (`command-types.ts`) no tiene campo de descripción, y con
 * razón: el descriptor es la máquina de estados, invariante entre idiomas,
 * y meterle prosa lo convertiría en el sitio donde la prosa envejece. La
 * paleta sí necesita una línea por comando —un menú de 182 nombres a secas no
 * orienta a nadie— así que la prosa vive aquí, aparte, con un contrato.
 *
 * ## El contrato es FAIL-CLOSED
 *
 * Todo comando del registro tiene su resumen o está en la lista de exclusión
 * EXPLÍCITA (hoy vacía). `command-summaries.spec.ts` recorre el registro real
 * y falla si alguien registra un comando mudo — así un comando nuevo no puede
 * publicarse invisible-a-medias en la paleta. Y al revés: un resumen cuyo
 * comando ya no existe también falla, para que este catálogo no acumule
 * cadáveres. En ejecución, `cadCommandSummary` lanza en vez de devolver una
 * cadena vacía: el silencio no es una opción, es el bug que este archivo mata.
 */

/** Nombre canónico → una línea en español. Mismo orden que el registro. */
export const CAD_COMMAND_SUMMARIES: Readonly<Record<string, string>> = {
  "-DSETTINGS": "Ayudas al dibujo por la línea de comandos: forzado, rejilla y orto, sin cuadro.",
  "-LAYER": "Capas por la línea de comandos: crear, activar, colorear, encender o bloquear.",
  "-LINETYPE": "Tipos de línea por la línea de comandos: listar, cargar y fijar el actual.",
  "-OSNAP": "Referencias a objetos por la línea: los catorce modos, separados por comas.",
  "-TOOLPALETTES": "Lista el contenido de una paleta de herramientas por la línea de comandos.",
  "-UCSMAN": "SCU con nombre por la línea de comandos: guardar, restituir, universal o listar.",
  "3DFORBIT": "Órbita 3D libre, sin restricción de eje.",
  "3DORBIT": "Órbita 3D alrededor del modelo.",
  "3DPAN": "Encuadre de la vista 3D.",
  "3DZOOM": "Zoom de la vista 3D.",
  ADCENTER: "DesignCenter: bloques y contenido de otros dibujos del despacho.",
  ADDSELECTED: "Dibuja uno como el designado: misma orden, misma capa, mismo color y tipo de línea.",
  ALIGN: "Alinea objetos con otros por pares de puntos de origen y destino.",
  ARC: "Arco por tres puntos o por centro, inicio y fin.",
  AREA: "Área y perímetro de un contorno o de los puntos designados.",
  ARRAY: "Matriz rectangular, polar o de camino con la selección.",
  ARRAYEDIT: "Edita una matriz asociativa existente.",
  ATTDEF: "Define un atributo de bloque: la etiqueta que pide valor al insertar.",
  ATTEDIT: "Edita los valores de atributo de una referencia de bloque.",
  ATTSYNC:
    "Pone al día los atributos de las referencias de un bloque redefinido.",
  AUDIT: "Revisa el dibujo: geometría degenerada, referencias colgantes y objetos sin usar; repara al confirmar.",
  AUTOCONSTRAIN: "Aplica restricciones geométricas automáticas a la selección.",
  BASE: "Fija el punto base de inserción del dibujo.",
  BEDIT: "Abre el panel de bloques para editar una definición (BLOCK redefine).",
  BLEND: "Fusiona dos curvas abiertas con una spline tangente o suave.",
  BLOCK: "Crea o redefine un bloque con los objetos designados.",
  BOUNDARY: "Genera una polilínea de contorno desde un punto interior.",
  BOX: "Caja: dos esquinas y una altura; también Centro, Cubo y Longitud.",
  BREAK: "Parte un objeto en dos, con o sin hueco.",
  BURST: "Estalla un bloque conservando sus atributos como texto real, no como el rótulo del tag.",
  CABLETRAY: "Charola de cables a doble línea con esquinas a inglete y eje.",
  CELTSCALE: "Escala de tipo de línea de los objetos nuevos.",
  CHAMFER: "Chaflán entre dos líneas con distancias dadas.",
  CHAMFEREDGE: "Chaflán sobre las aristas de un sólido.",
  CHECKSTANDARDS: "Compara capas y estilos de texto/cota contra el estándar del despacho.",
  CHPROP: "Cambia color, capa, tipo de línea, escala o grosor de la selección desde el teclado.",
  CIRCLE: "Círculo por centro y radio o diámetro.",
  COLOR: "Color actual de los objetos nuevos.",
  CONE: "Cono: centro, radio y altura; Radio superior para un tronco.",
  COPY: "Copia la selección con desplazamiento por dos puntos.",
  COPYBASE: "Copia al portapapeles de geometría con el punto base que se precise.",
  COPYCLIP: "Copia la selección al portapapeles de geometría (Ctrl+C); se pega aquí o en otro dibujo.",
  CUTCLIP: "Corta la selección al portapapeles de geometría (Ctrl+X).",
  CYLINDER: "Cilindro: centro, radio o diámetro y altura.",
  DATAEXTRACTION: "Cuadro de cantidades del modelo, a tabla o a CSV.",
  DCANGULAR: "Restricción paramétrica de cota angular.",
  DCDIAMETER: "Restricción paramétrica de cota de diámetro.",
  DCLINEAR: "Restricción paramétrica de cota lineal.",
  DCRADIUS: "Restricción paramétrica de cota de radio.",
  DDEDIT: "Edita el texto de un rótulo existente.",
  DELCONSTRAINT: "Borra las restricciones de los objetos designados.",
  DIM: "Modo de acotación continua: cotas encadenadas sin repetir la orden.",
  DIMALIGNED: "Cota alineada con la distancia real entre dos puntos.",
  DIMANGULAR: "Cota angular entre dos líneas o por vértice.",
  DIMARC: "Cota de longitud de arco.",
  DIMBASELINE: "Cotas en paralelo desde una base común.",
  DIMCONSTRAINT: "Convierte una cota en restricción paramétrica.",
  DIMCONTINUE: "Cotas encadenadas a continuación de la última.",
  DIMDIAMETER: "Cota de diámetro de círculo o arco.",
  DIMEDIT: "Edita texto y oblicuidad de cotas existentes.",
  DIMLINEAR: "Cota lineal horizontal o vertical.",
  DIMORDINATE: "Cota por coordenada (X o Y) desde el origen.",
  DIMRADIUS: "Cota de radio de círculo o arco.",
  DIMSTYLE: "Gestor de estilos de cota.",
  DIST: "Distancia y ángulo entre dos puntos.",
  DIVIDE: "Reparte puntos o bloques a partes iguales sobre un objeto.",
  DONUT: "Corona circular rellena por diámetros interior y exterior.",
  DOOR: "Puerta alojada en un muro, con hoja y abatimiento.",
  DRAWORDER: "Orden de dibujo: traer al frente o enviar al fondo.",
  DSETTINGS: "Cuadro de ayudas al dibujo: forzado, rejilla, polar y referencias.",
  DUCT: "Ducto de aire a doble línea con esquinas a inglete y eje: inyección, retorno, extracción.",
  DXFIN: "Importa un archivo DXF al dibujo.",
  DXFOUT: "Exporta el dibujo a DXF.",
  ELLIPSE: "Elipse por sus ejes, o arco elíptico.",
  ERASE: "Borra la selección.",
  ETRANSMIT: "Empaqueta el dibujo abierto —y lo que se resuelva de sus xrefs e imágenes— en un ZIP con manifiesto.",
  EXPLODE: "Descompone polilíneas, bloques, cotas y directrices en sus piezas.",
  EXPORT: "Exporta el dibujo a otros formatos.",
  EXTEND: "Alarga objetos hasta un borde de corte.",
  EXTRUDE: "Extruye un perfil cerrado a sólido 3D.",
  FILLET: "Empalme entre dos objetos con radio dado.",
  FILLETEDGE: "Redondeo sobre las aristas de un sólido.",
  FILTER: "Filtros de selección con nombre, reutilizables.",
  FLATSHOT: "Aplana el modelo 3D a un dibujo 2D acotable.",
  GCCOINCIDENT: "Restricción geométrica: puntos coincidentes.",
  GCCOLLINEAR: "Restricción geométrica: colineal.",
  GCCONCENTRIC: "Restricción geométrica: concéntrico.",
  GCEQUAL: "Restricción geométrica: igualdad de medida.",
  GCFIX: "Restricción geométrica: fijo en su sitio.",
  GCHORIZONTAL: "Restricción geométrica: horizontal.",
  GCPARALLEL: "Restricción geométrica: paralelo.",
  GCPERPENDICULAR: "Restricción geométrica: perpendicular.",
  GCSMOOTH: "Restricción geométrica: continuidad suave (G2).",
  GCSYMMETRIC: "Restricción geométrica: simétrico respecto de un eje.",
  GCTANGENT: "Restricción geométrica: tangente.",
  GCVERTICAL: "Restricción geométrica: vertical.",
  GEOMCONSTRAINT: "Aplica una restricción geométrica eligiendo el tipo.",
  GETVAR: "Lee el valor de una variable de sistema.",
  GRADIENT: "Relleno degradado de un contorno.",
  GROUP: "Agrupa la selección en un grupo con nombre.",
  HATCH: "Sombreado de un contorno con patrón o relleno sólido.",
  ID: "Coordenadas del punto designado.",
  IMAGE: "Inserta una imagen rasterizada como referencia.",
  IMPORT: "Importa geometría de otros formatos.",
  INSERT: "Inserta un bloque con punto, escala y giro.",
  INTERFERE: "Interferencias entre sólidos: dónde chocan.",
  INTERSECT: "Intersección booleana de sólidos o regiones.",
  JOIN: "Une líneas colineales, arcos concéntricos o tramos encadenados.",
  LAYER: "Gestor de capas.",
  LAYERSTATE: "Estados de capa con nombre: guarda y restituye combinaciones.",
  LAYFRZ: "Congela la capa del objeto designado.",
  LAYISO: "Aísla: apaga todas las capas menos las de los objetos designados.",
  LAYMCH: "Iguala la capa de los objetos designados a la de un objeto de destino.",
  LAYMRG: "Fusiona una capa en otra: reasigna sus objetos y la purga.",
  LAYOFF: "Desactiva la capa del objeto designado.",
  LAYON: "Activa todas las capas desactivadas.",
  LAYTHW: "Descongela todas las capas congeladas.",
  LAYTRANS: "Traduce las capas de un dibujo ajeno a las del despacho, con mapa guardable.",
  LAYUNISO: "Deshace el aislamiento de LAYISO restituyendo la visibilidad previa.",
  LAYWALK: "Recorre las capas mostrando una sola cada vez; Espacio avanza.",
  LAYOUT: "Crea, renombra o borra presentaciones (láminas).",
  LEADER: "Directriz simple con texto.",
  LENGTHEN: "Cambia la longitud de un objeto abierto.",
  LINE: "Línea por segmentos encadenados.",
  LINETYPE: "Carga tipos de línea y fija el actual.",
  LIST: "Propiedades del objeto designado, en texto.",
  LOFT: "Sólido por secciones transversales.",
  LTSCALE: "Escala global de los tipos de línea.",
  LWEIGHT: "Grosor de línea actual.",
  MASSPROP: "Propiedades de masa de regiones y sólidos.",
  MATCHPROP: "Copia las propiedades de un objeto a otros (pincel).",
  MEASURE: "Reparte puntos o bloques a distancia fija sobre un objeto.",
  MEPSYMBOL: "Símbolo MEP como bloque: válvula, difusor, rejilla, luminaria, contacto, tablero.",
  AEWIRE: "Conductor con su circuito y calibre; el número lo pone el dibujo, no usted.",
  AEWIRELIST: "Lista los conductores por circuito y CAZA los números repetidos. No escribe nada.",
  AECIRCUIT: "Protección, tensión y fases de un circuito, estampadas en todos sus conductores.",
  AECHECK: "Revisa los circuitos contra la NOM: ampacidad y caída de tensión con la longitud del plano.",
  AETAG: "Etiqueta un componente, o TODOS los que falten, con el número que le toca por familia.",
  AETAGLIST: "Dice qué componentes no llevan etiqueta y qué etiquetas se repiten. No escribe nada.",
  PIDLINE: "Línea de proceso con su número: diámetro, servicio, correlativo del dibujo y especificación.",
  PIDLIST: "Lista de líneas con su metrado del plano, y los errores que no piden catálogo. No escribe.",
  PIDEQUIP: "Equipo de proceso colocado Y etiquetado en un acto: el correlativo lo pone el dibujo.",
  PIDEQUIPLIST: "Lista los equipos, las etiquetas repetidas y los que no llevan. No escribe nada.",
  PIDROUTE: "Tiende tubería en 3D con su cota: el montante sale solo al cambiar de elevación.",
  PIDMTO: "Lista de materiales sacada del modelo: metros de tubo y accesorios deducidos. No escribe.",
  PIDISO: "Isométrico de una línea con longitudes verdaderas, lista de materiales y su hoja.",
  BLOQUEDIN: "Coloca un bloque DINÁMICO: una familia con parámetros en vez de veinte bloques casi iguales.",
  BLOQUEDINSET: "Cambia un parámetro de un bloque dinámico ya colocado, sin moverlo ni volver a insertarlo.",
  BLOQUEDINLIST: "Dice qué bloques dinámicos hay y con qué valores. No escribe nada.",
  BLOQUEDINDEF: "Vuelve dinámico un bloque TUYO: declara un parámetro de estirado dentro de su definición.",
  REFEDIT: "Saca la geometría de un bloque AL DIBUJO para editarla en sitio, sin explotarlo.",
  REFSET: "Añade a la edición en sitio lo que dibujaste nuevo, o retira lo que sobra.",
  REFCLOSE: "Cierra la edición en sitio: guarda en la definición o descarta.",
  ACTRECORD: "Empieza a grabar lo que tecleas como macro: los puntos se guardan como coordenadas.",
  ACTSTOP: "Cierra la grabación y guarda el macro como un guión .scr legible.",
  ACTMANAGER: "Lista los macros grabados en la sesión y repite uno.",
  FIELD: "Texto que se rellena solo: área, longitud, fecha o variable, sacados del dibujo.",
  UPDATEFIELD: "Vuelve a resolver los campos del dibujo; lo que no se puede resolver se cuenta.",
  GEOGRAPHICLOCATION: "Georreferencia el dibujo: un punto y su Este/Norte UTM o su latitud y longitud, con zona y datum.",
  MAPIMPORT: "Importa un shapefile o GeoJSON al dibujo como entidades con atributos, en el sistema del dibujo.",
  IMAGEATTACH: "Adjunta un plano escaneado (PNG, JPEG…) dentro del dibujo: inserción, ancho y giro.",
  IMAGECLIP: "Recorta una imagen por polígono o rectángulo, o quita el recorte.",
  IMAGEADJUST: "Brillo, contraste y atenuación de una imagen (0 a 100), o los restablece.",
  MIRROR: "Simetría de la selección respecto de un eje.",
  MLEADER: "Directriz múltiple con texto.",
  MLEADERSTYLE: "Gestor de estilos de directriz.",
  MOVE: "Mueve la selección por dos puntos.",
  MSPACE: "Entra al espacio modelo dentro de la ventana de la lámina.",
  MTEXT: "Texto multilínea con formato.",
  MVIEW: "Crea ventanas gráficas en la presentación.",
  NCOPY: "Copia una entidad de dentro de un bloque sin explotarlo.",
  NORMAMX: "Aplica la norma de dibujo mexicana al dibujo actual.",
  OFFSET: "Paralela a distancia exacta de la selección.",
  OPTIONS: "Opciones del editor.",
  OSNAP: "Cuadro de referencias a objetos: los catorce modos.",
  OVERKILL: "Limpia duplicados y solapes de la selección.",
  PAGESETUP: "Configura papel, márgenes, plumas y orientación de la lámina.",
  PAN: "Encuadre: desplaza la vista sin cambiar la escala.",
  PARAMETERS: "Parámetros del dibujo para restricciones dimensionales.",
  PASTECLIP: "Pega el portapapeles de geometría en el punto que se precise (Ctrl+V).",
  PASTEORIG: "Pega el portapapeles de geometría en sus coordenadas originales.",
  PEDIT: "Edita polilíneas: unir, cerrar, mover vértices.",
  PIPE: "Tubería en planta por servicio: capa y tipo de línea con texto; el diámetro va al cuadro.",
  PLAN: "Vuelve la vista a la planta del SCU actual.",
  PLINE: "Polilínea con tramos rectos y curvos.",
  PLOT: "Traza la lámina a PDF con escala exacta.",
  POINT: "Punto aislado.",
  POLYGON: "Polígono regular inscrito o circunscrito.",
  POLYSOLID: "Muro al vuelo: recorrido de tramos rectos con ancho y altura, o desde una línea.",
  PRESSPULL: "Empuja o tira de un contorno para crear un sólido.",
  PROPERTIES: "Paleta de propiedades de la selección.",
  PSPACE: "Vuelve al espacio papel desde la ventana.",
  PUBLISH: "Publica un conjunto de planos en un único PDF paginado, con portada e índice.",
  PURGE: "Purga definiciones sin uso: capas, bloques, estilos.",
  PYRAMID: "Pirámide: lados, radio de la base y altura; Radio superior para un tronco.",
  QDIM: "Acotación rápida: cadena continua entre los extremos de la selección.",
  QLEADER: "Directriz rápida de un tramo con su nota, sin el menú de MLEADER.",
  QSELECT: "Selección rápida por propiedades.",
  RAY: "Semirrecta: infinita hacia un solo lado.",
  RECOVER: "Rescata lo que se pueda de un documento canónico dañado, con manifiesto de lo perdido.",
  RECTANG: "Rectángulo por dos esquinas.",
  REDO: "Rehace lo último deshecho.",
  REGEN: "Regenera la vista actual.",
  REGENALL: "Regenera todas las vistas.",
  REGION: "Convierte contornos cerrados en regiones.",
  RENAME: "Renombra capas, bloques, estilos y demás tablas.",
  REVCLOUD: "Nube de revisión.",
  REVOLVE: "Sólido de revolución desde un perfil.",
  ROOF: "Cubierta a cuatro, dos o un agua sobre un rectángulo: pendiente, alero, planta y sólido.",
  ROTATE: "Gira la selección alrededor de un punto base.",
  RSCRIPT: "Repite el guion (.scr) en curso.",
  SCALE: "Escala la selección desde un punto base.",
  SCRIPT: "Ejecuta un guion .scr de órdenes.",
  SECTION: "Sección de un sólido por un plano.",
  SELECTSIMILAR: "Designa todo lo del mismo tipo y capa (y bloque) que lo designado.",
  SETBYLAYER: "Devuelve color, tipo de línea y grosor de la selección a PorCapa.",
  SETVAR: "Escribe una variable de sistema.",
  SHEETSET: "Gestiona el conjunto de planos: añade hojas, renumera y lee el índice.",
  SLAB: "Losa por contorno cerrado: espesor bajo la cota de la cara superior.",
  SLICE: "Rebana un sólido por un plano.",
  SOLDRAW: "Dibuja dentro de las vistas creadas por SOLVIEW.",
  SOLID: "Triángulos y cuadriláteros rellenos 2D.",
  SOLIDEDIT: "Edición de sólidos: extruir una cara, comprobar un cuerpo o separar una unión.",
  SOLPROF: "Perfil 2D de un sólido en la ventana.",
  SOLVIEW: "Ventanas de vistas derivadas del sólido: planta, alzado, sección.",
  SPHERE: "Esfera: centro y radio o diámetro.",
  SPLINE: "Curva libre por puntos de ajuste o vértices de control.",
  SPLINEDIT: "Edita una spline: vértices, cerrar, invertir.",
  STAIR: "Escalera recta paramétrica: contrahuellas por reglamento, huella por Blondel; planta y sólido.",
  STRETCH: "Estira lo capturado por la ventana sin despegar lo demás.",
  STYLE: "Gestor de estilos de texto.",
  STYLESMANAGER: "Lista las tablas de plumas cargadas y carga el .ctb o .stb del despacho.",
  SUBTRACT: "Resta booleana de sólidos o regiones.",
  SWEEP: "Sólido por barrido de un perfil a lo largo de un camino.",
  TABLE: "Tabla editable con filas y columnas.",
  TABLEDIT: "Cambia el texto de una celda de una tabla.",
  TABLESTYLE: "Gestor de estilos de tabla.",
  TEXT: "Texto de una sola línea.",
  TEXTALIGN: "Alinea texto existente sobre una recta definida por dos puntos.",
  TOLERANCE: "Marco de tolerancia geométrica (GD&T).",
  STDPART: "Normalizado como bloque: tornillo ISO 4017, tuerca ISO 4032, rondana ISO 7089.",
  STEELSHAPE: "Sección de perfil de acero como bloque: PTR, OC, LI, CPS, IPR por sus medidas.",
  BALLOON: "Globo de lista de materiales sobre una pieza, numerado solo.",
  BOM: "Lista de materiales: normalizados insertados y globos, como tabla.",
  WELDSYMBOL: "Símbolo de soldadura ISO 2553 / AWS: tipo, lado, tamaño, longitud, cola.",
  SURFACESYMBOL: "Símbolo de acabado superficial ISO 1302 con Ra y dirección de estrías.",
  DIMTOLERANCE: "Tolerancia de fabricación en cotas: simétrica, desviaciones, límites o ajuste ISO 286.",
  TOOLPALETTES: "Paletas de herramientas.",
  TORUS: "Toro: centro, radio del toro y radio del tubo.",
  TRIM: "Recorta objetos contra bordes de corte.",
  UCS: "Define el sistema de coordenadas personal (SCU).",
  UCSICON: "Muestra u oculta el icono del SCU.",
  UCSMAN: "Gestor de SCU con nombre.",
  UNGROUP: "Deshace un grupo.",
  UNION: "Unión booleana de sólidos o regiones.",
  UNITS: "Unidades y precisión del dibujo.",
  VIEW: "Vistas con nombre: guarda y restituye encuadres.",
  VPLAYER: "Congela o descongela capas SÓLO en una ventana de la presentación.",
  VPOINT: "Punto de vista 3D por vector.",
  U: "Deshace la última operación. Sin preguntar, como en AutoCAD.",
  UNDO: "Deshace varias operaciones de una vez; una por defecto.",
  VSCURRENT: "Estilo visual de la vista: alámbrico, oculto, sombreado.",
  WALL: "Muro paramétrico con espesor y altura.",
  WBLOCK: "Publica la selección como bloque de la biblioteca del despacho.",
  WEDGE: "Cuña: dos esquinas y una altura; la cara inclinada baja a lo largo de X.",
  WINDOW: "Ventana alojada en un muro, con antepecho.",
  WIPEOUT: "Máscara que tapa lo que queda debajo.",
  XATTACH: "Adjunta una referencia externa (xref).",
  XBIND: "Incorpora al dibujo definiciones de una xref.",
  XCLIP: "Recorta la vista de una xref o de un bloque.",
  XLINE: "Recta infinita de construcción.",
  XPLODE: "Descompone eligiendo capa, color y tipo de línea de las piezas, o heredándolos del bloque.",
  XREF: "Gestor de referencias externas.",
  ZOOM: "Acerca o aleja: extensión, ventana, escala.",
};

/**
 * Exclusiones EXPLÍCITAS del contrato: comandos registrados que a propósito no
 * aparecen en la paleta. Hoy no hay ninguno — si algún día lo hay, su nombre
 * se escribe aquí con un comentario del porqué, no se calla el spec.
 */
export const CAD_COMMAND_SUMMARY_EXCLUSIONS: ReadonlySet<string> = new Set();

/**
 * El resumen de un comando, o un error con nombre. Fail-closed a propósito:
 * devolver una cadena vacía dejaría el comando mudo en la paleta y nadie lo
 * notaría hasta que un usuario lo buscase; lanzar hace que lo note el CI.
 */
export function cadCommandSummary(name: string): string {
  const summary = CAD_COMMAND_SUMMARIES[name.trim().toUpperCase()];
  if (!summary)
    throw new Error(
      `El comando ${name.trim().toUpperCase()} no tiene resumen en command-summaries.ts. ` +
        "Todo comando del registro necesita su línea en español (o una exclusión explícita) " +
        "antes de publicarse: la paleta no enseña comandos mudos.",
    );
  return summary;
}
