/**
 * METADATOS de los 291 comandos del registro. GENERADO — no se edita a mano.
 *
 * Lo escribe `node scripts/cad/build-command-manifest.mjs --write` importando los
 * 106 módulos REALES de `./commands/*` en Node, y `--check` —enganchado en
 * `npm run check:cad`— falla si lo committeado deja de coincidir con lo que los
 * descriptores dicen hoy. Regla 4 de la campaña de cimientos: ninguna cifra vive
 * en dos lugares, y un comando nuevo no puede entrar sin aparecer aquí.
 *
 * ## Qué hace aquí
 *
 * La cinta (`ribbon.ts`), la paleta Ctrl+K (`command-palette.ts`), la asistencia
 * de la línea de comandos y los tres gates que cuentan comandos leen `name`,
 * `aliases` y `kind` AL ABRIR el estudio. La máquina de estados `begin`/`step`
 * no la necesita nadie hasta que alguien teclea una orden. Así que los
 * metadatos viajan estáticos y la implementación llega por
 * `lazy-commands.ts` — el mismo reparto que `lib/cad/commands/lazy.ts`.
 *
 * `module` es el id del módulo que implementa el comando: lo que
 * `loadCadCommand(nombre)` necesita para saber qué `import()` disparar.
 */
import type { CadCommandKind, CadSelectionRule } from "./command-types";
import type { CadCommandModuleId } from "./lazy-commands";

export interface CadCommandManifestEntry {
  name: string;
  aliases: readonly string[];
  kind: CadCommandKind;
  transparent: boolean;
  selection: CadSelectionRule;
  repeatable: boolean;
  mutates: boolean;
  spatial?: boolean | "elevation";
  cursor?: "crosshair" | "pick" | "none";
  /** Módulo que trae `begin`/`step`. Su `import()` vive en `lazy-commands.ts`. */
  module: CadCommandModuleId;
}

export const CAD_COMMAND_MANIFEST: readonly CadCommandManifestEntry[] = [
  { name: "DIMBASELINE", aliases: ["DBA"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimension-chains" },
  { name: "DIMCONTINUE", aliases: ["DCO"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimension-chains" },
  { name: "DIM", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-dimension-chains" },
  { name: "DIMEDIT", aliases: ["DED"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-dimension-chains" },
  { name: "DIMLINEAR", aliases: ["DLI"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimensions" },
  { name: "DIMALIGNED", aliases: ["DAL"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimensions" },
  { name: "DIMANGULAR", aliases: ["DAN"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimensions-angular" },
  { name: "DIMARC", aliases: ["DAR"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-dimensions-angular" },
  { name: "DIMRADIUS", aliases: ["DRA"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-dimensions-radial" },
  { name: "DIMDIAMETER", aliases: ["DDI"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-dimensions-radial" },
  { name: "DIMORDINATE", aliases: ["DOR"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-dimensions-radial" },
  { name: "HATCH", aliases: ["H", "BH"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-hatch" },
  { name: "GRADIENT", aliases: ["GD"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-hatch" },
  { name: "BOUNDARY", aliases: ["BO"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-hatch" },
  { name: "MLEADER", aliases: ["MLD"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-leaders" },
  { name: "LEADER", aliases: ["LE"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-leaders" },
  { name: "QDIM", aliases: ["QD"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-quick" },
  { name: "TEXTALIGN", aliases: ["TA"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-quick" },
  { name: "QLEADER", aliases: ["QL"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-quickleader" },
  { name: "STYLE", aliases: ["ST"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/annotate-styles" },
  { name: "DIMSTYLE", aliases: ["D", "DST", "DDIM"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/annotate-styles" },
  { name: "MLEADERSTYLE", aliases: ["MLS"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/annotate-styles" },
  { name: "TABLESTYLE", aliases: ["TS"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/annotate-styles" },
  { name: "TABLEDIT", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-table-edit" },
  { name: "TEXT", aliases: ["DT", "DTEXT"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-text" },
  { name: "MTEXT", aliases: ["T", "MT"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-text" },
  { name: "DDEDIT", aliases: ["ED", "TEXTEDIT"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/annotate-text" },
  { name: "TOLERANCE", aliases: ["TOL"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/annotate-tolerance" },
  { name: "ROOF", aliases: ["ROOFADD", "CUBIERTA"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/architecture-roof" },
  { name: "SLAB", aliases: ["SLABADD", "LOSA"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/architecture-roof" },
  { name: "STAIR", aliases: ["STAIRADD", "ESCALERA"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/architecture-stair" },
  { name: "ACTRECORD", aliases: ["GRABARACCION"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/automation-actions" },
  { name: "ACTSTOP", aliases: ["PARARACCION"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/automation-actions" },
  { name: "ACTMANAGER", aliases: ["GESTORACCIONES"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/automation-actions" },
  { name: "SCRIPT", aliases: ["SCR"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/automation-script" },
  { name: "RSCRIPT", aliases: ["RS"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/automation-script" },
  { name: "BLOCK", aliases: ["B", "BMAKE"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/blocks" },
  { name: "WBLOCK", aliases: ["W"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/blocks" },
  { name: "BASE", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "crosshair", module: "commands/blocks" },
  { name: "INSERT", aliases: ["I", "DDINSERT"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/blocks" },
  { name: "ATTEDIT", aliases: ["ATE", "ATTE", "EATTEDIT"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/blocks" },
  { name: "ATTSYNC", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/blocks" },
  { name: "BURST", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/blocks-burst" },
  { name: "BEDIT", aliases: ["BE"], kind: "manage", transparent: false, selection: "optional", repeatable: false, mutates: true, cursor: "pick", module: "commands/blocks-edit" },
  { name: "COPYCLIP", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/clipboard" },
  { name: "CUTCLIP", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/clipboard" },
  { name: "COPYBASE", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/clipboard" },
  { name: "PASTECLIP", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/clipboard" },
  { name: "PASTEORIG", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/clipboard" },
  { name: "COMPARE", aliases: ["DWGCOMPARE", "COMPARAR"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/compare-drawings" },
  { name: "DATAEXTRACTION", aliases: ["DX"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/data-extraction-commands" },
  { name: "REVISA", aliases: ["ENTREGA", "PREFLIGHT"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/delivery-review" },
  { name: "ADCENTER", aliases: ["AC", "ADC", "DC"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/design-center" },
  { name: "DIMTOLERANCE", aliases: ["TOLERANCIA", "DTOL"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/dimension-tolerance" },
  { name: "ATTDEF", aliases: ["ATT"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-annotation-v4" },
  { name: "TABLE", aliases: ["TB"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-annotation-v4" },
  { name: "LINE", aliases: ["L"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/draw-basics" },
  { name: "CIRCLE", aliases: ["C"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/draw-basics" },
  { name: "XLINE", aliases: ["XL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-construction" },
  { name: "RAY", aliases: [], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-construction" },
  { name: "ARC", aliases: ["A"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/draw-curves" },
  { name: "ELLIPSE", aliases: ["EL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-curves" },
  { name: "POLYGON", aliases: ["POL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-curves" },
  { name: "SOLID", aliases: ["SO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-fills" },
  { name: "WIPEOUT", aliases: ["WIPE"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-fills" },
  { name: "IMAGE", aliases: ["IM"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-fills" },
  { name: "DOOR", aliases: ["PUERTA", "DOORADD"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-opening" },
  { name: "WINDOW", aliases: ["VENTANA", "WINDOWADD"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-opening" },
  { name: "PLINE", aliases: ["PL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/draw-pline" },
  { name: "POINT", aliases: ["PO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-points" },
  { name: "DIVIDE", aliases: ["DIV"], kind: "draw", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/draw-points" },
  { name: "MEASURE", aliases: ["ME"], kind: "draw", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/draw-points" },
  { name: "RECTANG", aliases: ["REC", "RECTANGLE"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/draw-rectang" },
  { name: "DONUT", aliases: ["DO", "DONUTS"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-rings" },
  { name: "REVCLOUD", aliases: ["REVC"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-rings" },
  { name: "SPLINE", aliases: ["SPL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-spline" },
  { name: "WALL", aliases: ["WA", "MURO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/draw-wall" },
  { name: "FIELD", aliases: ["CAMPO"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/drawing-fields" },
  { name: "UPDATEFIELD", aliases: ["ACTUALIZARCAMPO"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "none", module: "commands/drawing-fields" },
  { name: "BLOQUEDIN", aliases: ["BLOQUEDINAMICO", "DYNBLOCK"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/dynamic-block" },
  { name: "BLOQUEDINSET", aliases: ["PARAMETROBLOQUE", "DYNSET"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "none", module: "commands/dynamic-block" },
  { name: "BLOQUEDINLIST", aliases: ["LISTABLOQUESDIN"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/dynamic-block" },
  { name: "BLOQUEDINDEF", aliases: ["PARAMETRODEF", "DYNPARAM"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/dynamic-block" },
  { name: "AECIRCUIT", aliases: ["CIRCUITO"], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/electrical-circuit" },
  { name: "AECHECK", aliases: ["REVISARNOM", "NOMCHECK"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/electrical-circuit" },
  { name: "AETAG", aliases: ["ETIQUETA", "AECOMPONENT"], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "pick", module: "commands/electrical-tag" },
  { name: "AETAGLIST", aliases: ["LISTAETIQUETAS"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/electrical-tag" },
  { name: "AEWIRE", aliases: ["CONDUCTOR", "WIRENUMBER"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/electrical-wire" },
  { name: "AEWIRELIST", aliases: ["LISTACONDUCTORES"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/electrical-wire" },
  { name: "ETRANSMIT", aliases: ["ETRANS"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/etransmit-commands" },
  { name: "BREAKLINE", aliases: ["ROTURA"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/express-tools" },
  { name: "FLATTEN", aliases: ["APLASTAR"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/express-tools" },
  { name: "LAYDEL", aliases: ["CAPABORRAR"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/express-tools" },
  { name: "TCOUNT", aliases: ["NUMTEXTO"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/express-tools" },
  { name: "TXT2MTXT", aliases: ["TEXTOAMTEXTO"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/express-tools" },
  { name: "GEOGRAPHICLOCATION", aliases: ["GEO", "GEOLOCATION", "MAPCSASSIGN", "GEORREFERENCIAR"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/geo-location" },
  { name: "GROUP", aliases: ["G"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/groups" },
  { name: "UNGROUP", aliases: ["UNG"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/groups" },
  { name: "PURGE", aliases: ["PU"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/groups" },
  { name: "U", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/history-commands" },
  { name: "REDO", aliases: ["MREDO"], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/history-commands" },
  { name: "UNDO", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/history-commands" },
  { name: "LIST", aliases: ["LI", "LS"], kind: "inquiry", transparent: false, selection: "required", repeatable: true, mutates: false, cursor: "pick", module: "commands/inquiry-list" },
  { name: "MASSPROP", aliases: ["MASS"], kind: "inquiry", transparent: false, selection: "required", repeatable: true, mutates: false, cursor: "pick", module: "commands/inquiry-list" },
  { name: "DIST", aliases: ["DI"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/inquiry-measure" },
  { name: "ID", aliases: [], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/inquiry-measure" },
  { name: "AREA", aliases: ["AA"], kind: "inquiry", transparent: false, selection: "none", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/inquiry-measure" },
  { name: "REGION", aliases: ["REG"], kind: "draw", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/inquiry-region" },
  { name: "DXFIN", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/interop-dxf" },
  { name: "DXFOUT", aliases: [], kind: "inquiry", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "none", module: "commands/interop-dxf" },
  { name: "LAYOUT", aliases: ["LO"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/layout-commands" },
  { name: "MVIEW", aliases: ["MV"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/layout-commands" },
  { name: "MSPACE", aliases: ["MS"], kind: "view", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/layout-commands" },
  { name: "PSPACE", aliases: ["PS"], kind: "view", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/layout-commands" },
  { name: "AUDIT", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/manage-audit" },
  { name: "LAYTRANS", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/manage-laytrans" },
  { name: "RECOVER", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/manage-recover" },
  { name: "CHECKSTANDARDS", aliases: ["STANDARDS", "CHK"], kind: "inquiry", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/manage-standards" },
  { name: "MAPIMPORT", aliases: ["IMPORTARGIS"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/map-import" },
  { name: "BALLOON", aliases: ["AMBALLOON", "GLOBO"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-annotate" },
  { name: "BOM", aliases: ["AMBOM", "LISTAMATERIALES"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-annotate" },
  { name: "STDPART", aliases: ["AMCONTENTLIB", "NORMALIZADO", "TORNILLO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-parts" },
  { name: "STEELSHAPE", aliases: ["AMSTLSHAP2D", "PERFIL", "PERFILACERO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-parts" },
  { name: "WELDSYMBOL", aliases: ["AMWELDSYM", "SOLDADURA"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-symbols" },
  { name: "SURFACESYMBOL", aliases: ["AMSURFSYM", "ACABADO"], kind: "annotate", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mechanical-symbols" },
  { name: "MEPSYMBOL", aliases: ["DEVICEADD", "SIMBOLOMEP"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mep-symbol" },
  { name: "PIPE", aliases: ["PIPEADD", "TUBERIA"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mep-tracing" },
  { name: "DUCT", aliases: ["DUCTADD", "DUCTO"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mep-tracing" },
  { name: "CABLETRAY", aliases: ["CABLETRAYADD", "CHAROLA"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/mep-tracing" },
  { name: "ALIGN", aliases: ["AL"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-align" },
  { name: "MATCHPROP", aliases: ["MA"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-align" },
  { name: "ARRAY", aliases: ["AR", "ARR"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-array" },
  { name: "ARRAYEDIT", aliases: [], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-array" },
  { name: "ERASE", aliases: ["E"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-basics" },
  { name: "MOVE", aliases: ["M"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-basics" },
  { name: "COPY", aliases: ["CO", "CP"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-basics" },
  { name: "OFFSET", aliases: ["O"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-basics" },
  { name: "BLEND", aliases: ["BLE"], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-blend" },
  { name: "OVERKILL", aliases: ["OV"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-cleanup" },
  { name: "DRAWORDER", aliases: ["DR"], kind: "modify", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-cleanup" },
  { name: "TRIM", aliases: ["TR"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-edges" },
  { name: "EXTEND", aliases: ["EX"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-edges" },
  { name: "BREAK", aliases: ["BR"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-edges" },
  { name: "XPLODE", aliases: ["XP"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-foreign" },
  { name: "SETBYLAYER", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-foreign" },
  { name: "CHPROP", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-foreign" },
  { name: "NCOPY", aliases: [], kind: "modify", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-foreign" },
  { name: "JOIN", aliases: ["J"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-join" },
  { name: "EXPLODE", aliases: ["X"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-join" },
  { name: "MIRROR", aliases: ["MI"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-mirror" },
  { name: "PEDIT", aliases: ["PE"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-pedit" },
  { name: "SPLINEDIT", aliases: ["SPE"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-pedit" },
  { name: "STRETCH", aliases: ["S"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/modify-stretch" },
  { name: "LENGTHEN", aliases: ["LEN"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-stretch" },
  { name: "ROTATE", aliases: ["RO"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-transform" },
  { name: "SCALE", aliases: ["SC"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-transform" },
  { name: "FILLET", aliases: ["F"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-transform" },
  { name: "CHAMFER", aliases: ["CHA"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/modify-transform" },
  { name: "DIMCONSTRAINT", aliases: ["DCON"], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-dimensions" },
  { name: "DCLINEAR", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-dimensions" },
  { name: "DCRADIUS", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-dimensions" },
  { name: "DCDIAMETER", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-dimensions" },
  { name: "DCANGULAR", aliases: [], kind: "annotate", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-dimensions" },
  { name: "PARAMETERS", aliases: ["PARAM"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/parametric-dimensions" },
  { name: "GEOMCONSTRAINT", aliases: ["GCON"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCHORIZONTAL", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCVERTICAL", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCFIX", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCCOINCIDENT", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCCOLLINEAR", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCCONCENTRIC", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCPARALLEL", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCPERPENDICULAR", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCTANGENT", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCEQUAL", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCSMOOTH", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "GCSYMMETRIC", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "AUTOCONSTRAIN", aliases: [], kind: "manage", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "DELCONSTRAINT", aliases: [], kind: "manage", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "pick", module: "commands/parametric-geometry" },
  { name: "PDFATTACH", aliases: ["ADJUNTARPDF"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/pdf-underlay-commands" },
  { name: "PDFIMPORT", aliases: ["IMPORTARPDF"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/pdf-underlay-commands" },
  { name: "PDFCLIP", aliases: ["RECORTARPDF"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFADJUST", aliases: ["AJUSTARPDF"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFPAGE", aliases: ["PAGINAPDF"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFSCALE", aliases: ["ESCALARPDF"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/pdf-underlay-commands" },
  { name: "PDFDETACH", aliases: ["DESADJUNTARPDF"], kind: "manage", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFUNLOAD", aliases: ["DESCARGARPDF"], kind: "manage", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFRELOAD", aliases: ["RECARGARPDF"], kind: "manage", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/pdf-underlay-commands" },
  { name: "PDFLIST", aliases: ["LISTARPDF"], kind: "inquiry", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/pdf-underlay-commands" },
  { name: "PIDEQUIP", aliases: ["EQUIPO", "EQUIPMENT"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/plant-equipment" },
  { name: "PIDEQUIPLIST", aliases: ["LISTAEQUIPOS"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/plant-equipment" },
  { name: "PIDISO", aliases: ["ISOMETRICO", "ISOGEN"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/plant-iso" },
  { name: "PIDLINE", aliases: ["LINEAPROCESO", "LINENUMBER"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/plant-line" },
  { name: "PIDLIST", aliases: ["LISTALINEAS", "PLANTDATAMANAGER"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/plant-line" },
  { name: "PIDROUTE", aliases: ["RUTATUBERIA", "ROUTEPIPE"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/plant-route" },
  { name: "PIDMTO", aliases: ["LISTAMATERIAL", "PIPEBOM"], kind: "inquiry", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/plant-route" },
  { name: "PAGESETUP", aliases: ["PSET"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/plot-commands" },
  { name: "PLOT", aliases: ["PRINT", "PLO"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "crosshair", module: "commands/plot-commands" },
  { name: "STYLESMANAGER", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/plot-commands" },
  { name: "IMAGEATTACH", aliases: ["IAT"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/raster-image" },
  { name: "IMAGECLIP", aliases: ["ICL"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/raster-image" },
  { name: "IMAGEADJUST", aliases: ["IAD"], kind: "modify", transparent: false, selection: "command-first", repeatable: true, mutates: true, cursor: "pick", module: "commands/raster-image" },
  { name: "REFEDIT", aliases: ["EDITARREF"], kind: "manage", transparent: false, selection: "optional", repeatable: false, mutates: true, cursor: "pick", module: "commands/reference-edit" },
  { name: "REFSET", aliases: ["CONJUNTOREF"], kind: "manage", transparent: false, selection: "required", repeatable: true, mutates: true, cursor: "none", module: "commands/reference-edit" },
  { name: "REFCLOSE", aliases: ["CERRARREF"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/reference-edit" },
  { name: "QSELECT", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "none", module: "commands/select-query" },
  { name: "FILTER", aliases: ["FI"], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "none", module: "commands/select-query" },
  { name: "SELECTSIMILAR", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/select-similar" },
  { name: "ADDSELECTED", aliases: [], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/select-similar" },
  { name: "VPLAYER", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "LAYISO", aliases: [], kind: "manage", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/settings-layer-tools" },
  { name: "LAYUNISO", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "LAYFRZ", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "pick", module: "commands/settings-layer-tools" },
  { name: "LAYTHW", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "LAYOFF", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "pick", module: "commands/settings-layer-tools" },
  { name: "LAYON", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "LAYMCH", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/settings-layer-tools" },
  { name: "LAYWALK", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "LAYMRG", aliases: [], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-layer-tools" },
  { name: "NORMAMX", aliases: ["CAPASMX"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-mexican-standard" },
  { name: "LAYER", aliases: ["LA", "DDLMODES"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "PROPERTIES", aliases: ["CH", "MO", "PR", "DDMODIFY"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "DSETTINGS", aliases: ["DS", "SE", "RM", "DDRMODES"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "OSNAP", aliases: ["OS", "DDOSNAP"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "OPTIONS", aliases: ["OP", "PREFERENCES", "PR-OPTIONS"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "TOOLPALETTES", aliases: ["TP"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "UCSMAN", aliases: ["UC", "DDUCS"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "LINETYPE", aliases: ["LT", "DDLTYPE"], kind: "manage", transparent: true, selection: "optional", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "-LAYER", aliases: ["-LA"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-palettes" },
  { name: "LAYERSTATE", aliases: ["LAS", "LMAN"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-palettes" },
  { name: "RENAME", aliases: ["REN", "DDRENAME"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/settings-palettes" },
  { name: "-DSETTINGS", aliases: ["-DS", "-SE", "-RM"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "-OSNAP", aliases: ["-OS"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "-UCSMAN", aliases: ["-UC", "UCSNAMED"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "-TOOLPALETTES", aliases: ["-TP"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "-LINETYPE", aliases: ["-LT"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-palettes" },
  { name: "UNITS", aliases: ["UN", "DDUNITS"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "LTSCALE", aliases: ["LTS"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "CELTSCALE", aliases: [], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "LWEIGHT", aliases: ["LW"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "COLOR", aliases: ["COL", "COLOUR", "DDCOLOR"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "SETVAR", aliases: ["SET"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "GETVAR", aliases: [], kind: "inquiry", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/settings-variables" },
  { name: "PUBLISH", aliases: ["PUBLICAR"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/sheet-set-commands" },
  { name: "SHEETSET", aliases: ["SSM"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/sheet-set-commands" },
  { name: "EXTRUDE", aliases: ["EXT"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-create" },
  { name: "REVOLVE", aliases: ["REV"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-create" },
  { name: "SOLIDEDIT", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-edit" },
  { name: "FLATSHOT", aliases: ["APLANAR"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/solids-flatshot" },
  { name: "SOLPROF", aliases: ["PERFILSOL"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, spatial: true, cursor: "pick", module: "commands/solids-flatshot" },
  { name: "SWEEP", aliases: [], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-inquiry" },
  { name: "LOFT", aliases: [], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-inquiry" },
  { name: "INTERFERE", aliases: ["INF"], kind: "inquiry", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/solids-inquiry" },
  { name: "IMPORT", aliases: ["IMP"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/solids-interop" },
  { name: "EXPORT", aliases: ["EXP"], kind: "inquiry", transparent: false, selection: "optional", repeatable: true, mutates: false, cursor: "pick", module: "commands/solids-interop" },
  { name: "UNION", aliases: ["UNI"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "SUBTRACT", aliases: ["SU"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "INTERSECT", aliases: ["IN"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "FILLETEDGE", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "CHAMFEREDGE", aliases: [], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "SLICE", aliases: ["SL"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "SECTION", aliases: ["SEC"], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-modify" },
  { name: "BOX", aliases: [], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "WEDGE", aliases: ["WE"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "CYLINDER", aliases: ["CYL"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "CONE", aliases: [], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "SPHERE", aliases: [], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "TORUS", aliases: ["TOR"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "PYRAMID", aliases: ["PYR"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "POLYSOLID", aliases: ["PSOLID"], kind: "draw", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: "elevation", cursor: "crosshair", module: "commands/solids-primitives" },
  { name: "PRESSPULL", aliases: [], kind: "draw", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/solids-push-face" },
  { name: "SOLVIEW", aliases: ["SOLV", "VISTASOL"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, spatial: true, cursor: "crosshair", module: "commands/solview-commands" },
  { name: "SOLDRAW", aliases: ["SOLD", "DIBUJOSOL"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "none", module: "commands/solview-commands" },
  { name: "UCS", aliases: ["SCU"], kind: "manage", transparent: true, selection: "none", repeatable: false, mutates: false, spatial: true, cursor: "crosshair", module: "commands/ucs-commands" },
  { name: "UCSICON", aliases: [], kind: "view", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/ucs-view-commands" },
  { name: "PLAN", aliases: [], kind: "view", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/ucs-view-commands" },
  { name: "ZOOM", aliases: ["Z"], kind: "view", transparent: true, selection: "optional", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/view-navigation" },
  { name: "PAN", aliases: ["P"], kind: "view", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/view-navigation" },
  { name: "VIEW", aliases: ["V"], kind: "view", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/view-navigation" },
  { name: "REGEN", aliases: ["RE"], kind: "view", transparent: false, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/view-navigation" },
  { name: "REGENALL", aliases: ["REA"], kind: "view", transparent: false, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/view-navigation" },
  { name: "3DORBIT", aliases: ["3DO", "ORBIT"], kind: "view", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/view-navigation-3d" },
  { name: "3DFORBIT", aliases: ["3DF", "FORBIT"], kind: "view", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/view-navigation-3d" },
  { name: "3DPAN", aliases: ["3DP"], kind: "view", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "crosshair", module: "commands/view-navigation-3d" },
  { name: "3DZOOM", aliases: ["3DZ"], kind: "view", transparent: true, selection: "none", repeatable: true, mutates: false, cursor: "none", module: "commands/view-navigation-3d" },
  { name: "VPOINT", aliases: ["VP"], kind: "view", transparent: true, selection: "none", repeatable: false, mutates: false, cursor: "none", module: "commands/view-navigation-3d" },
  { name: "VSCURRENT", aliases: ["SHADEMODE", "VS"], kind: "view", transparent: true, selection: "none", repeatable: false, mutates: false, module: "commands/view-visual" },
  { name: "XREF", aliases: ["XR", "EXTERNALREFERENCES"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/xrefs" },
  { name: "XATTACH", aliases: ["XA"], kind: "manage", transparent: false, selection: "none", repeatable: true, mutates: true, cursor: "crosshair", module: "commands/xrefs" },
  { name: "XBIND", aliases: ["XB"], kind: "manage", transparent: false, selection: "none", repeatable: false, mutates: true, cursor: "none", module: "commands/xrefs" },
  { name: "XCLIP", aliases: ["XC", "CLIP"], kind: "modify", transparent: false, selection: "optional", repeatable: true, mutates: true, cursor: "pick", module: "commands/xrefs" },
];
