/**
 * Rótulos cortos en español de los comandos del motor — el texto del BOTÓN de
 * la cinta.
 *
 * ## Por qué existe este archivo
 *
 * El botón de la cinta pintaba el nombre canónico en inglés (LINE, RECTANG,
 * MATCHPROP). En AutoCAD es-MX el botón dice «Línea», «Rectángulo», «Igualar
 * propiedades», y el nombre con su alias vive en el tooltip. El resumen
 * (`command-summaries.ts`) es una frase; aquí va lo que cabe en un botón:
 * una o dos palabras, tres como mucho.
 *
 * ## El contrato es FAIL-CLOSED, igual que el de los resúmenes
 *
 * Todo comando del registro tiene rótulo y ningún rótulo nombra un comando
 * que ya no existe (`command-labels.spec.ts`). `cadCommandLabel` lanza en
 * vez de devolver una cadena vacía: un botón mudo no es una opción.
 *
 * ## Qué dice cada rótulo
 *
 * Lo que el comando HACE en este producto, no lo que promete el nombre:
 * PLOT traza a PDF y por eso dice «Trazar a PDF»; los comandos con guion
 * («-LAYER») trabajan por la línea de comandos y lo dicen entre paréntesis.
 * Los botones pequeños de la cinta miden 7 rem (`w-28`, `CadRibbonButton.tsx`):
 * tras el icono y el hueco, el rótulo tiene 88 px hasta el borde del botón, y
 * el golden 214 falla si lo pasa. 16 caracteres es sólo la cota gruesa que
 * comprueba `command-labels.spec.ts`: el Chromium de Linux del CI pinta Inter
 * 500 a 11 px hasta un 5 % más ancho que el de Windows, y «Adjuntar imagen»
 * (15), que en Windows mide 87 px, allí midió ~90 y tumbó el golden. Un
 * rótulo pequeño a la vista a 1366 o 1280 px no pasa de 83 px medido en
 * Windows. Los primarios se pintan grandes, con el rótulo en dos líneas, y
 * ahí lo que manda es que ninguna palabra pase de 12 caracteres.
 */

/** Nombre canónico → rótulo del botón. Orden alfabético, como el registro. */
export const CAD_COMMAND_LABELS: Readonly<Record<string, string>> = {
  "-DSETTINGS": "Ayudas (línea)",
  "-LAYER": "Capas (línea)",
  "-LINETYPE": "Tipos (línea)",
  "-OSNAP": "Refent (línea)",
  "-TOOLPALETTES": "Paleta (línea)",
  "-UCSMAN": "SCU (línea)",


  "3DFACE": "Cara 3D",
  "3DFLY": "Volar 3D",
  "3DFORBIT": "Órbita libre",
  "3DMOVE": "Mover 3D",
  "3DARRAY": "Arreglo 3D",
  "3DORBIT": "Órbita 3D",
  "3DPAN": "Encuadre 3D",
  "3DROTATE": "Rotar 3D",
  "3DSCALE": "Escalar 3D",
  "3DALIGN": "Alinear 3D",

  "3DSWIVEL": "Girar vista",
  "3DWALK": "Caminar 3D",
  "3DZOOM": "Zoom 3D",
  ABOUT: "Acerca de",
  ACTMANAGER: "Macros",
  ACTRECORD: "Grabar macro",
  ACTSTOP: "Parar macro",
  ADCENTER: "DesignCenter",
  ADDSELECTED: "Dibujar igual",
  AECHECK: "Revisar NOM",
  AECIRCUIT: "Circuito",
  AESYMBOL: "Eléctrico",
  AETAG: "Etiquetar",
  AETAGLIST: "Listar etiquetas",
  AEWIRE: "Conductor",
  AEWIRELIST: "Listar cables",
  ALIGN: "Alinear",
  ARC: "Arco",
  AREA: "Área",
  ARRAY: "Matriz",
  ARRAYEDIT: "Editar matriz",
  ATTDEF: "Definir atributo",
  ATTEDIT: "Editar atributo",
  ATTSYNC: "Sincronizar",
  AUDIT: "Auditar",
  AUTOCONSTRAIN: "Automáticas",
  BALLOON: "Globo",
  BASE: "Punto base",
  BEDIT: "Editar bloque",
  BLEND: "Fusionar curvas",
  BLOCK: "Crear bloque",
  BLOQUEDIN: "Bloque dinámico",
  BLOQUEDINDEF: "Hacer dinámico",
  BLOQUEDINLIST: "Listar dinámicos",
  BLOQUEDINSET: "Fijar parámetro",
  BOM: "Materiales",
  BOUNDARY: "Contorno",
  BOX: "Caja",
  BREAK: "Partir",
  BREAKATPOINT: "Partir punto",
  BREAKLINE: "Línea de rotura",
  BURST: "Estallar",
  CABLETRAY: "Charola",
  CAMERA: "Cámara",

  CELTSCALE: "Escala objeto",
  CENTERLINE: "Eje de centro",
  CENTERMARK: "Marca de centro",
  CHAMFER: "Chaflán",
  CHAMFEREDGE: "Chaflán arista",
  CHECKSTANDARDS: "Validar normas",
  CHPROP: "Cambiar (línea)",
  CIRCLE: "Círculo",
  COGO: "Poligonal",
  COLOR: "Color",
  COMPARE: "Comparar",
  CONE: "Cono",
  CONVTOMESH: "A malla",
  CONVTOSOLID: "A sólido",
  CONVTOSURFACE: "A superficie",
  COPY: "Copiar",
  COPYBASE: "Copiar con base",
  COPYCLIP: "Copiar Ctrl+C",
  CUADROCONSTRUCCION: "Cuadro rumbos",
  CUTCLIP: "Cortar Ctrl+X",
  CYLINDER: "Cilindro",
  DATAEXTRACTION: "Cantidades",
  DCANGULAR: "Angular",
  DCDIAMETER: "Diámetro",
  DCLINEAR: "Lineal",
  DCRADIUS: "Radio",
  DDEDIT: "Editar texto",
  DELCONSTRAINT: "Eliminar",
  DIM: "Modo acotar",
  DIMALIGNED: "Cota alineada",
  DIMANGULAR: "Cota angular",
  DIMARC: "Longitud arco",
  DIMBASELINE: "Línea base",
  DIMCONSTRAINT: "Convertir cota",
  DIMCONTINUE: "Continuar",
  DIMDIAMETER: "Cota diámetro",
  DIMEDIT: "Editar cota",
  DIMLINEAR: "Cota lineal",
  DIMORDINATE: "Coordenada",
  DIMRADIUS: "Cota de radio",
  DIMSTYLE: "Estilo de cota",
  DIMTOLERANCE: "Tolerancia cota",
  DIST: "Distancia",
  DISTANTLIGHT: "Luz direccional",
  DIVIDE: "Dividir",
  DONUT: "Arandela",
  DOOR: "Puerta",
  DRAWORDER: "Orden de dibujo",
  DSETTINGS: "Ayudas dibujo",
  DUCT: "Ducto",
  DVIEW: "Vista dinámica",

  DXFIN: "Importar DXF",
  DXFOUT: "Exportar DXF",
  ELLIPSE: "Elipse",
  ERASE: "Borrar",
  ETRANSMIT: "Empaquetar",
  EXPLODE: "Descomponer",
  EXPORT: "Exportar",
  EXTEND: "Alargar",
  EXTRUDE: "Extruir",
  FIELD: "Campo",
  FILLET: "Empalme",
  FILLETEDGE: "Empalme arista",
  FIND: "Buscar texto",
  FILL: "Relleno",
  FILTER: "Filtro",
  FLATSHOT: "Aplanar a 2D",
  FLATTEN: "Aplastar a Z=0",
  GCCOINCIDENT: "Coincidente",
  GCCOLLINEAR: "Colineal",
  GCCONCENTRIC: "Concéntrico",
  GCEQUAL: "Igual",
  GCFIX: "Fijo",
  GCHORIZONTAL: "Horizontal",
  GCPARALLEL: "Paralelo",
  GCPERPENDICULAR: "Perpendicular",
  GCSMOOTH: "Suave",
  GCSYMMETRIC: "Simétrico",
  GCTANGENT: "Tangente",
  GCVERTICAL: "Vertical",
  GEOGRAPHICLOCATION: "Geolocalizar",
  GEOMCONSTRAINT: "Restricción",
  GETVAR: "Leer variable",
  GRADIENT: "Degradado",
  GROUP: "Agrupar",
  HATCH: "Sombreado",
  ID: "Coordenadas",
  IMAGE: "Imagen",
  IMAGEADJUST: "Ajustar ráster",
  IMAGEATTACH: "Adjuntar ráster",
  IMAGECLIP: "Recortar ráster",
  IMPORT: "Importar",
  INSERT: "Insertar",
  INTERFERE: "Interferencias",
  INTERSECT: "Intersección",
  JOIN: "Unir",
  LAYCUR: "Capa actual",
  LAYDEL: "Borrar capa",
  LAYER: "Gestor de capas",
  LAYERSTATE: "Estados de capa",
  LAYFRZ: "Congelar",
  LAYISO: "Aislar",
  LAYMCH: "Igualar capa",
  LAYMRG: "Fusionar capa",
  LAYOFF: "Desactivar",
  LAYON: "Activar todas",
  LAYOUT: "Presentaciones",
  LAYTHW: "Descongelar",
  LAYTRANS: "Traducir capas",
  LAYUNISO: "Deshacer aislar",
  LAYWALK: "Recorrer capas",
  LEADER: "Directriz simple",
  LENGTHEN: "Longitud",
  LINE: "Línea",
  LINETYPE: "Tipo de línea",
  LIST: "Listar",
  LOFT: "Solevar",
  LTSCALE: "Escala global",
  LWEIGHT: "Grosor de línea",
  MAPIMPORT: "Importar GIS",
  MASSPROP: "Masa y volumen",
  MATCHPROP: "Igualar propiedades",
  MATERIALS: "Materiales",
  MATERIALATTACH: "Asignación",
  MATERIALMAP: "Mapeado",
  MEASURE: "Graduar",
  MESH: "Malla",

  MEPSYMBOL: "Símbolo MEP",
  MIRROR: "Simetría",
  MIRROR3D: "Simetría 3D",

  MLEADER: "Directriz nota",
  MLEADERSTYLE: "Estilo directriz",
  MOVE: "Desplazar",
  MSPACE: "Espacio modelo",
  MTEXT: "Texto multilínea",
  MVIEW: "Ventana gráfica",

  NCOPY: "Copiar anidado",
  NORMAMX: "Norma México",
  NAVBAR: "Navegación",
  NAVVCUBE: "Cubo 3D",
  OFFSET: "Desfase",
  OPTIONS: "Opciones",
  OSNAP: "Referencias",
  OVERKILL: "Duplicados",
  PAGESETUP: "Preparar hoja",
  PAN: "Encuadre",
  PARAMETERS: "Parámetros",
  PASTECLIP: "Pegar Ctrl+V",
  PASTEORIG: "Pegar en origen",
  PERSPECTIVE: "Perspectiva",
  PDFADJUST: "Ajustar PDF",
  PDFATTACH: "Adjuntar PDF",
  PDFCLIP: "Recortar PDF",
  PDFDETACH: "Desadjuntar PDF",
  PDFIMPORT: "Importar PDF",
  PDFLIST: "Listar PDF",
  PDFPAGE: "Página PDF",
  PDFRELOAD: "Recargar PDF",
  PDFSCALE: "Escalar PDF",
  PDFUNLOAD: "Descargar PDF",
  PEDIT: "Editar polilínea",
  PIDEQUIP: "Equipo",
  PIDEQUIPLIST: "Listar equipos",
  PIDISO: "Isométrico",
  PIDLINE: "Línea proceso",
  PIDLIST: "Listar líneas",
  PIDMTO: "Materiales tubo",
  PIDROUTE: "Tubería 3D",
  PIPE: "Tubería",
  PLAN: "Planta",
  PLANESURF: "Superficie plana",
  PLINE: "Polilínea",
  PLOT: "Trazar a PDF",
  POINT: "Punto",
  POINTLIGHT: "Luz puntual",
  POLYGON: "Polígono",
  POLYSOLID: "Polisólido",
  PRESSPULL: "Pulsar y tirar",
  PROPERTIES: "Propiedades",
  PSPACE: "Espacio papel",
  PUBLISH: "Publicar",
  PURGE: "Limpiar",
  PYRAMID: "Pirámide",
  QDIM: "Acotación rápida",
  QLEADER: "Directriz rápida",
  QSELECT: "Selección rápida",
  RAY: "Rayo",
  RECOVER: "Recuperar",
  RECTANG: "Rectángulo",
  MREDO: "Rehacer varios",
  REDO: "Rehacer",
  REFCLOSE: "Cerrar edición",
  REFEDIT: "Editar en sitio",
  REFSET: "Conjunto edición",
  REDRAW: "Redibujar",
  REGEN: "Regenerar",
  REGENALL: "Regenerar todo",
  REGION: "Región",
  RENDER: "Renderizar",
  RENDERCROP: "Recorte render",
  RENDERENVIRONMENT: "Entorno render",
  RENDEREXPOSURE: "Exposición",
  RENDERPRESETS: "Calidad render",
  RENDERWIN: "Ventana render",
  RENAME: "Renombrar",

  REVCLOUD: "Nube de revisión",
  REVERSE: "Invertir",
  REVISA: "Revisar entrega",
  REVOLVE: "Revolución",
  ROOF: "Cubierta",
  ROTATE: "Girar",
  RSCRIPT: "Repetir guion",
  REVSURF: "Sup. revolución",
  MESHSMOOTH: "Suavizar malla",
  MESHSMOOTHMORE: "Más suave",
  MESHSMOOTHLESS: "Menos suave",
  MESHREFINE: "Refinar malla",
  MESHCOLLAPSE: "Colapsar malla",
  MESHCAP: "Tapar malla",
  MESHMERGE: "Unir mallas",
  MESHSPLIT: "Dividir malla",
  MESHUNCREASE: "Quitar crestas",
  MESHCREASE: "Marcar crestas",
  MESHEXTRUDE: "Extruir malla",
  EDGESURF: "Superf. borde",
  RULESURF: "Superficie reglada",
  SCALE: "Escala",
  SCRIPT: "Ejecutar guion",
  SECTION: "Sección",
  SELECTSIMILAR: "Designar similar",
  SETBYLAYER: "Poner PorCapa",
  SETVAR: "Fijar variable",
  SHEETSET: "Lista de planos",
  SLAB: "Losa",
  SLICE: "Rebanar",
  SOLDRAW: "Dibujar vistas",
  SOLID: "Sólido 2D",
  SOLIDEDIT: "Editar sólido",
  SOLPROF: "Perfil 2D",
  SOLVIEW: "Vista de sólido",
  SPHERE: "Esfera",
  STATUS: "Estado",

  SPLINE: "Spline",
  SPLINEDIT: "Editar spline",
  SPOTLIGHT: "Foco",
  STAIR: "Escalera",
  STDPART: "Normalizado",
  STEELSHAPE: "Perfil de acero",
  STRETCH: "Estirar",
  STYLE: "Estilo de texto",
  STYLESMANAGER: "Tablas plumas",
  SUBTRACT: "Diferencia",
  SUNPROPERTIES: "Propiedades sol",
  SURFACESYMBOL: "Acabado",
  SURFOFFSET: "Vaciar sólido",
  SURFTRIM: "Recortar sup",
  SURFUNTRIM: "Restaurar sup",
  SURFPATCH: "Parchear sup",
  SURFNETWORK: "Red de sup",
  SURFBLEND: "Mezclar sup",
  SURFEXTEND: "Extender sup",
  SURFFILLET: "Filete sup",
  SURFSCULPT: "Esculpir sup",
  SWEEP: "Barrido",
  TABLE: "Tabla",
  TABLEDIT: "Editar celda",
  TABLESTYLE: "Estilo de tabla",
  TABSURF: "Tabulada",
  TCOUNT: "Numerar textos",
  TEXT: "Texto",
  TEXTALIGN: "Alinear texto",
  TIME: "Tiempo",

  TOLERANCE: "Tolerancia",
  TOOLPALETTES: "Paletas",
  TORUS: "Toroide",
  TRIM: "Recortar",
  TXT2MTXT: "Fundir textos",
  U: "Deshacer",
  UCS: "SCU",
  UCSICON: "Icono SCU",
  UCSMAN: "Gestor SCU",
  UNDO: "Deshacer varios",
  UNGROUP: "Desagrupar",
  UNION: "Unión",
  UNITS: "Unidades",
  UPDATEFIELD: "Actualizar campo",
  VECTORIZE: "Vectorizar",
  VIEW: "Vista guardada",
  VIEWBASE: "Vista base",
  VIEWDETAIL: "Detalle",
  VIEWEDIT: "Editar vista",
  VIEWPROJ: "Proyección",
  VIEWSECTION: "Sección",
  VIEWUPDATE: "Actualizar vista",
  VIEWRES: "Resolución vista",
  VISUALSTYLES: "Estilos visuales",
  VPLAYER: "Capas en ventana",
  VPOINT: "Punto de vista",
  VSCURRENT: "Estilo visual",
  WALL: "Muro",
  WBLOCK: "Publicar bloque",
  WEDGE: "Cuña",
  WELDSYMBOL: "Soldadura",
  WINDOW: "Ventana",
  WIPEOUT: "Máscara",
  XATTACH: "Adjuntar xref",
  XBIND: "Incorporar xref",
  XCLIP: "Recortar xref",
  XLINE: "Recta",
  XPLODE: "Explotar a capa",
  XREF: "Gestor de xref",
  ZOOM: "Zoom",
};

/** Rótulo del botón; lanza si el comando no tiene (el silencio no es opción). */
export function cadCommandLabel(name: string): string {
  const label = CAD_COMMAND_LABELS[name.toUpperCase()];
  if (!label) throw new Error(`el comando ${name.toUpperCase()} no tiene rótulo en command-labels.ts`);
  return label;
}
