import "./unit/ac1015-header.spec.js";
import "./unit/ac1015-object-map.spec.js";
import "./unit/ac1015-writer.spec.js";
import "./unit/api.spec.js";
import "./unit/binary.spec.js";
import "./unit/bitcodes.spec.js";
import "./unit/entities-core.spec.js";
import "./unit/model.spec.js";
import "./unit/security.spec.js";
