export type CadSymbolCategory =
  | "equipment"
  | "flow"
  | "safety"
  | "storage"
  | "operator"
  // CAD universal (AXOS-CAD-UNIVERSAL-001): cualquiera diseñando cualquier
  // cosa — no solo plantas EMS.
  | "architecture"
  | "furniture"
  | "office"
  | "commerce";
export interface CadSymbolPort {
  id: string;
  label: string;
  x: number;
  y: number;
}
export interface CadSymbolDefinition {
  id: string;
  label: string;
  category: CadSymbolCategory;
  defaultWidth: number;
  defaultHeight: number;
  layer: string;
  tags: string[];
  ports: CadSymbolPort[];
}
export interface CadSymbolPlacement {
  id: string;
  symbolId: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
  layer: string;
  tags: string[];
}

export const CAD_SYMBOL_LIBRARY: CadSymbolDefinition[] = [
  {
    id: "smt-line",
    label: "SMT line",
    category: "equipment",
    defaultWidth: 12000,
    defaultHeight: 2400,
    layer: "Equipment",
    tags: ["smt", "line"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "solder-paste-printer",
    label: "Solder paste printer",
    category: "equipment",
    defaultWidth: 2500,
    defaultHeight: 1700,
    layer: "Equipment",
    tags: ["smt", "printer", "paste", "front-end"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "spi",
    label: "SPI",
    category: "equipment",
    defaultWidth: 1800,
    defaultHeight: 1500,
    layer: "Equipment",
    tags: ["smt", "inspection", "quality", "paste"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "pick-and-place",
    label: "Pick-and-place",
    category: "equipment",
    defaultWidth: 3600,
    defaultHeight: 2000,
    layer: "Equipment",
    tags: ["smt", "placement", "machine", "line"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "reflow-oven",
    label: "Reflow oven",
    category: "equipment",
    defaultWidth: 6200,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["smt", "thermal", "oven", "line"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "xray-inspection",
    label: "X-ray inspection",
    category: "equipment",
    defaultWidth: 2200,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["quality", "xray", "inspection", "npi"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
      { id: "reject", label: "Reject", x: 0, y: 0.5 },
    ],
  },
  {
    id: "ict-tester",
    label: "ICT tester",
    category: "equipment",
    defaultWidth: 2600,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["test", "ict", "quality", "electronics"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
      { id: "fail", label: "Fail", x: 0, y: 0.5 },
    ],
  },
  {
    id: "functional-test-bench",
    label: "Functional test bench",
    category: "equipment",
    defaultWidth: 3000,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["test", "functional", "bench", "quality"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
      { id: "fail", label: "Fail", x: 0, y: 0.5 },
    ],
  },
  {
    id: "conformal-coating",
    label: "Conformal coating",
    category: "equipment",
    defaultWidth: 3200,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["coating", "protection", "smt", "process"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "depaneling-router",
    label: "Depaneling router",
    category: "equipment",
    defaultWidth: 2400,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["depaneling", "router", "post-smt", "process"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "manual-assembly-cell",
    label: "Manual assembly cell",
    category: "equipment",
    defaultWidth: 3600,
    defaultHeight: 2400,
    layer: "Equipment",
    tags: ["assembly", "manual", "cell", "operator"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "quality-gate",
    label: "Quality gate",
    category: "equipment",
    defaultWidth: 2400,
    defaultHeight: 1600,
    layer: "Equipment",
    tags: ["quality", "gate", "inspection", "release"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
      { id: "hold", label: "Hold", x: 0, y: 0.5 },
    ],
  },
  {
    id: "label-print-station",
    label: "Label print station",
    category: "equipment",
    defaultWidth: 1600,
    defaultHeight: 1200,
    layer: "Equipment",
    tags: ["packing", "label", "printer", "traceability"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "calibration-station",
    label: "Calibration station",
    category: "equipment",
    defaultWidth: 2200,
    defaultHeight: 1600,
    layer: "Equipment",
    tags: ["calibration", "quality", "metrology", "tooling"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "inspection",
    label: "Inspection",
    category: "equipment",
    defaultWidth: 2500,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["quality"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "aoi",
    label: "AOI",
    category: "equipment",
    defaultWidth: 1800,
    defaultHeight: 1600,
    layer: "Equipment",
    tags: ["inspection", "aoi"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "warehouse-rack",
    label: "Warehouse rack",
    category: "storage",
    defaultWidth: 4200,
    defaultHeight: 1100,
    layer: "Layout",
    tags: ["warehouse", "storage"],
    ports: [],
  },
  {
    id: "packing",
    label: "Packing",
    category: "equipment",
    defaultWidth: 3200,
    defaultHeight: 2200,
    layer: "Equipment",
    tags: ["packing"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "forklift-path",
    label: "Forklift path",
    category: "flow",
    defaultWidth: 10000,
    defaultHeight: 2500,
    layer: "Flow",
    tags: ["forklift", "aisle"],
    ports: [],
  },
  {
    id: "operator-station",
    label: "Operator station",
    category: "operator",
    defaultWidth: 1200,
    defaultHeight: 900,
    layer: "Equipment",
    tags: ["operator"],
    ports: [{ id: "work", label: "Work", x: 0, y: 0 }],
  },
  {
    id: "esd-area",
    label: "ESD area",
    category: "safety",
    defaultWidth: 5000,
    defaultHeight: 3500,
    layer: "Safety",
    tags: ["esd", "controlled"],
    ports: [],
  },
  {
    id: "safety-zone",
    label: "Safety zone",
    category: "safety",
    defaultWidth: 4000,
    defaultHeight: 3000,
    layer: "Safety",
    tags: ["safety"],
    ports: [],
  },
  {
    id: "conveyor",
    label: "Conveyor",
    category: "flow",
    defaultWidth: 6000,
    defaultHeight: 900,
    layer: "Flow",
    tags: ["conveyor"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "test-station",
    label: "Test station",
    category: "equipment",
    defaultWidth: 2200,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["test"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },
  {
    id: "rework-station",
    label: "Rework station",
    category: "equipment",
    defaultWidth: 2400,
    defaultHeight: 1900,
    layer: "Equipment",
    tags: ["rework"],
    ports: [
      { id: "in", label: "In", x: -0.5, y: 0 },
      { id: "out", label: "Out", x: 0.5, y: 0 },
    ],
  },

  // ── CAD universal (AXOS-CAD-UNIVERSAL-001): arquitectura y casa ──
  {
    id: "door-90",
    label: "Puerta 90 cm",
    category: "architecture",
    defaultWidth: 900,
    defaultHeight: 150,
    layer: "Architecture",
    tags: ["puerta", "door", "acceso", "casa", "oficina"],
    ports: [],
  },
  {
    id: "double-door-180",
    label: "Puerta doble 180 cm",
    category: "architecture",
    defaultWidth: 1800,
    defaultHeight: 150,
    layer: "Architecture",
    tags: ["puerta", "doble", "double door", "acceso"],
    ports: [],
  },
  {
    id: "window-120",
    label: "Ventana 120 cm",
    category: "architecture",
    defaultWidth: 1200,
    defaultHeight: 150,
    layer: "Architecture",
    tags: ["ventana", "window", "fachada"],
    ports: [],
  },
  {
    id: "stairs-straight",
    label: "Escalera recta",
    category: "architecture",
    defaultWidth: 1000,
    defaultHeight: 3000,
    layer: "Architecture",
    tags: ["escalera", "stairs", "nivel"],
    ports: [],
  },
  {
    id: "wc",
    label: "WC",
    category: "architecture",
    defaultWidth: 400,
    defaultHeight: 700,
    layer: "Architecture",
    tags: ["baño", "wc", "sanitario", "toilet"],
    ports: [],
  },
  {
    id: "sink",
    label: "Lavabo",
    category: "architecture",
    defaultWidth: 600,
    defaultHeight: 450,
    layer: "Architecture",
    tags: ["lavabo", "baño", "sink"],
    ports: [],
  },
  {
    id: "shower",
    label: "Regadera",
    category: "architecture",
    defaultWidth: 900,
    defaultHeight: 900,
    layer: "Architecture",
    tags: ["regadera", "ducha", "shower", "baño"],
    ports: [],
  },
  {
    id: "stove",
    label: "Estufa",
    category: "architecture",
    defaultWidth: 760,
    defaultHeight: 600,
    layer: "Architecture",
    tags: ["estufa", "cocina", "stove", "kitchen"],
    ports: [],
  },
  {
    id: "refrigerator",
    label: "Refrigerador",
    category: "architecture",
    defaultWidth: 700,
    defaultHeight: 700,
    layer: "Architecture",
    tags: ["refrigerador", "refri", "cocina", "fridge"],
    ports: [],
  },

  // ── Mobiliario de casa ──
  {
    id: "bed-single",
    label: "Cama individual",
    category: "furniture",
    defaultWidth: 1000,
    defaultHeight: 2000,
    layer: "Furniture",
    tags: ["cama", "recámara", "bed", "casa"],
    ports: [],
  },
  {
    id: "bed-queen",
    label: "Cama matrimonial",
    category: "furniture",
    defaultWidth: 1400,
    defaultHeight: 2000,
    layer: "Furniture",
    tags: ["cama", "matrimonial", "recámara", "queen bed"],
    ports: [],
  },
  {
    id: "sofa-3",
    label: "Sofá 3 plazas",
    category: "furniture",
    defaultWidth: 2100,
    defaultHeight: 900,
    layer: "Furniture",
    tags: ["sofá", "sala", "sofa", "couch"],
    ports: [],
  },
  {
    id: "dining-table-4",
    label: "Mesa comedor 4",
    category: "furniture",
    defaultWidth: 1200,
    defaultHeight: 800,
    layer: "Furniture",
    tags: ["comedor", "mesa", "dining table"],
    ports: [],
  },
  {
    id: "wardrobe",
    label: "Ropero",
    category: "furniture",
    defaultWidth: 1500,
    defaultHeight: 600,
    layer: "Furniture",
    tags: ["ropero", "clóset", "wardrobe", "recámara"],
    ports: [],
  },

  // ── Oficina ──
  {
    id: "desk",
    label: "Escritorio",
    category: "office",
    defaultWidth: 1200,
    defaultHeight: 600,
    layer: "Office",
    tags: ["escritorio", "oficina", "desk"],
    ports: [],
  },
  {
    id: "office-chair",
    label: "Silla de oficina",
    category: "office",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Office",
    tags: ["silla", "oficina", "chair"],
    ports: [],
  },
  {
    id: "file-cabinet",
    label: "Archivero",
    category: "office",
    defaultWidth: 500,
    defaultHeight: 600,
    layer: "Office",
    tags: ["archivero", "oficina", "file cabinet"],
    ports: [],
  },
  {
    id: "meeting-table-8",
    label: "Mesa de juntas 8",
    category: "office",
    defaultWidth: 2400,
    defaultHeight: 1200,
    layer: "Office",
    tags: ["juntas", "sala", "meeting", "conferencia"],
    ports: [],
  },

  // ── Comercio y restaurante ──
  {
    id: "counter",
    label: "Mostrador",
    category: "commerce",
    defaultWidth: 1800,
    defaultHeight: 600,
    layer: "Commerce",
    tags: ["mostrador", "tienda", "counter", "retail", "caja"],
    ports: [],
  },
  {
    id: "shelf-gondola",
    label: "Góndola / estante",
    category: "commerce",
    defaultWidth: 1200,
    defaultHeight: 500,
    layer: "Commerce",
    tags: ["góndola", "estante", "tienda", "shelf", "retail"],
    ports: [],
  },
  {
    id: "restaurant-table-4",
    label: "Mesa restaurante 4",
    category: "commerce",
    defaultWidth: 900,
    defaultHeight: 900,
    layer: "Commerce",
    tags: ["mesa", "restaurante", "comensales", "restaurant"],
    ports: [],
  },
  {
    id: "bar-counter",
    label: "Barra",
    category: "commerce",
    defaultWidth: 2400,
    defaultHeight: 600,
    layer: "Commerce",
    tags: ["barra", "bar", "restaurante", "cafetería"],
    ports: [],
  },
  // Segunda tanda universal (AXOS-CAD-UNIVERSAL-004): escuela, gimnasio,
  // exterior y baño público — medidas reales en mm, tags bilingües.
  {
    id: "school-desk",
    label: "Pupitre",
    category: "furniture",
    defaultWidth: 600,
    defaultHeight: 500,
    layer: "Furniture",
    tags: ["pupitre", "desk", "escuela", "school", "aula", "salón"],
    ports: [],
  },
  {
    id: "whiteboard",
    label: "Pizarrón 240 cm",
    category: "office",
    defaultWidth: 2400,
    defaultHeight: 100,
    layer: "Office",
    tags: ["pizarrón", "pizarron", "whiteboard", "escuela", "aula", "oficina"],
    ports: [],
  },
  {
    id: "treadmill",
    label: "Caminadora",
    category: "equipment",
    defaultWidth: 800,
    defaultHeight: 1900,
    layer: "Equipment",
    tags: ["caminadora", "treadmill", "gimnasio", "gym", "cardio"],
    ports: [],
  },
  {
    id: "weight-rack",
    label: "Rack de pesas",
    category: "equipment",
    defaultWidth: 1800,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["pesas", "rack", "gimnasio", "gym", "weights"],
    ports: [],
  },
  {
    id: "gym-bench",
    label: "Banco de gimnasio",
    category: "equipment",
    defaultWidth: 1200,
    defaultHeight: 500,
    layer: "Equipment",
    tags: ["banco", "bench", "gimnasio", "gym"],
    ports: [],
  },
  {
    id: "tree",
    label: "Árbol",
    category: "architecture",
    defaultWidth: 3000,
    defaultHeight: 3000,
    layer: "Architecture",
    tags: ["árbol", "arbol", "tree", "jardín", "jardin", "exterior", "paisaje"],
    ports: [],
  },
  {
    id: "outdoor-bench",
    label: "Banca exterior",
    category: "architecture",
    defaultWidth: 1500,
    defaultHeight: 550,
    layer: "Architecture",
    tags: ["banca", "bench", "exterior", "parque", "jardín", "jardin"],
    ports: [],
  },
  {
    id: "parking-spot",
    label: "Cajón de estacionamiento",
    category: "architecture",
    defaultWidth: 2500,
    defaultHeight: 5000,
    layer: "Architecture",
    tags: ["estacionamiento", "cajón", "cajon", "parking", "auto", "exterior"],
    ports: [],
  },
  {
    id: "urinal",
    label: "Mingitorio",
    category: "architecture",
    defaultWidth: 400,
    defaultHeight: 350,
    layer: "Architecture",
    tags: ["mingitorio", "urinal", "baño", "bano", "sanitario", "público"],
    ports: [],
  },
  {
    id: "toilet-stall",
    label: "Cubículo de baño",
    category: "architecture",
    defaultWidth: 900,
    defaultHeight: 1500,
    layer: "Architecture",
    tags: ["cubículo", "cubiculo", "stall", "baño", "bano", "sanitario", "público"],
    ports: [],
  },
  {
    id: "trough-sink",
    label: "Lavabo corrido",
    category: "architecture",
    defaultWidth: 1800,
    defaultHeight: 550,
    layer: "Architecture",
    tags: ["lavabo", "sink", "baño", "bano", "corrido", "público"],
    ports: [],
  },
  // — Tercera tanda universal (AXOS-CAD-UNIVERSAL-009): taller mecánico —
  {
    id: "car",
    label: "Auto",
    category: "equipment",
    defaultWidth: 1800,
    defaultHeight: 4500,
    layer: "Equipment",
    tags: ["auto", "coche", "carro", "car", "vehículo", "vehiculo", "taller"],
    ports: [],
  },
  {
    id: "car-lift",
    label: "Elevador de auto",
    category: "equipment",
    defaultWidth: 3400,
    defaultHeight: 4800,
    layer: "Equipment",
    tags: ["elevador", "lift", "rampa", "taller", "mecánico", "mecanico", "auto"],
    ports: [],
  },
  {
    id: "workbench",
    label: "Banco de trabajo",
    category: "equipment",
    defaultWidth: 1800,
    defaultHeight: 750,
    layer: "Equipment",
    tags: ["banco de trabajo", "workbench", "taller", "mesa de trabajo", "herramientas"],
    ports: [],
  },
  {
    id: "tool-cabinet",
    label: "Gabinete de herramientas",
    category: "equipment",
    defaultWidth: 700,
    defaultHeight: 450,
    layer: "Equipment",
    tags: ["gabinete", "herramientas", "tool", "cabinet", "taller", "carrito"],
    ports: [],
  },
  {
    id: "air-compressor",
    label: "Compresor de aire",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["compresor", "compressor", "aire", "taller", "neumático", "neumatico"],
    ports: [],
  },
  {
    id: "tire-rack",
    label: "Estante de llantas",
    category: "equipment",
    defaultWidth: 2000,
    defaultHeight: 500,
    layer: "Equipment",
    tags: ["llantas", "neumáticos", "neumaticos", "tire", "estante", "taller"],
    ports: [],
  },
  // — Cuarta tanda universal (AXOS-CAD-UNIVERSAL-012): salón de belleza —
  {
    id: "styling-chair",
    label: "Silla de estilista",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["estilista", "silla", "salón", "salon", "belleza", "barbería", "barberia"],
    ports: [],
  },
  {
    id: "wash-station",
    label: "Lavacabezas",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 1000,
    layer: "Equipment",
    tags: ["lavacabezas", "lavado", "shampoo", "salón", "salon", "belleza"],
    ports: [],
  },
  {
    id: "styling-mirror",
    label: "Tocador con espejo",
    category: "equipment",
    defaultWidth: 1200,
    defaultHeight: 450,
    layer: "Equipment",
    tags: ["tocador", "espejo", "estilista", "salón", "salon", "belleza"],
    ports: [],
  },
  // — Quinta tanda universal (AXOS-CAD-UNIVERSAL-015): panadería —
  {
    id: "oven",
    label: "Horno",
    category: "equipment",
    defaultWidth: 800,
    defaultHeight: 800,
    layer: "Equipment",
    tags: ["horno", "oven", "panadería", "panaderia", "cocina", "pizzería", "pizzeria"],
    ports: [],
  },
  {
    id: "dough-mixer",
    label: "Amasadora",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["amasadora", "mixer", "panadería", "panaderia", "masa"],
    ports: [],
  },
  {
    id: "display-case",
    label: "Vitrina",
    category: "commerce",
    defaultWidth: 1500,
    defaultHeight: 700,
    layer: "Commerce",
    tags: ["vitrina", "display", "mostrador", "panadería", "panaderia", "tienda"],
    ports: [],
  },
  // — Sexta tanda universal (AXOS-CAD-UNIVERSAL-016): veterinaria —
  {
    id: "kennel-cage",
    label: "Jaula para mascotas",
    category: "equipment",
    defaultWidth: 900,
    defaultHeight: 700,
    layer: "Equipment",
    tags: ["jaula", "kennel", "mascotas", "veterinaria", "hospitalización", "hospitalizacion"],
    ports: [],
  },
  // — Séptima tanda universal (AXOS-CAD-UNIVERSAL-017): lavandería —
  {
    id: "washer",
    label: "Lavadora",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["lavadora", "washer", "lavandería", "lavanderia", "ropa"],
    ports: [],
  },
  {
    id: "dryer",
    label: "Secadora",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["secadora", "dryer", "lavandería", "lavanderia", "ropa"],
    ports: [],
  },
  // — Octava tanda universal (AXOS-CAD-UNIVERSAL-018): guardería —
  {
    id: "crib",
    label: "Cuna",
    category: "furniture",
    defaultWidth: 700,
    defaultHeight: 1300,
    layer: "Furniture",
    tags: ["cuna", "crib", "guardería", "guarderia", "bebé", "bebe", "kinder"],
    ports: [],
  },
  // — Novena tanda universal (AXOS-CAD-UNIVERSAL-020): hotel —
  {
    id: "nightstand",
    label: "Buró",
    category: "furniture",
    defaultWidth: 450,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["buró", "buro", "nightstand", "mesa de noche", "recámara", "recamara", "hotel"],
    ports: [],
  },
  // — Décima tanda universal (AXOS-CAD-UNIVERSAL-021): consultorio dental —
  {
    id: "dental-chair",
    label: "Sillón dental",
    category: "equipment",
    defaultWidth: 900,
    defaultHeight: 1800,
    layer: "Equipment",
    tags: ["sillón dental", "sillon dental", "dental", "dentista", "consultorio"],
    ports: [],
  },
  // — Undécima tanda universal (AXOS-CAD-UNIVERSAL-023): deportes —
  {
    id: "goal",
    label: "Portería",
    category: "equipment",
    defaultWidth: 3000,
    defaultHeight: 1000,
    layer: "Equipment",
    tags: ["portería", "porteria", "goal", "fútbol", "futbol", "cancha", "deporte"],
    ports: [],
  },
  // — Duodécima tanda universal (AXOS-CAD-UNIVERSAL-024): fiestas —
  {
    id: "bounce-house",
    label: "Brincolín",
    category: "equipment",
    defaultWidth: 3000,
    defaultHeight: 3000,
    layer: "Equipment",
    tags: ["brincolín", "brincolin", "inflable", "bounce", "fiesta", "salón de fiestas", "salon de fiestas"],
    ports: [],
  },
  // — Decimotercera tanda universal (AXOS-CAD-UNIVERSAL-025): iglesia —
  {
    id: "pew",
    label: "Banca de iglesia",
    category: "furniture",
    defaultWidth: 2600,
    defaultHeight: 550,
    layer: "Furniture",
    tags: ["banca de iglesia", "pew", "iglesia", "templo", "capilla", "culto"],
    ports: [],
  },
  {
    id: "pulpit",
    label: "Púlpito",
    category: "furniture",
    defaultWidth: 800,
    defaultHeight: 600,
    layer: "Furniture",
    tags: ["púlpito", "pulpito", "pulpit", "iglesia", "templo", "altar"],
    ports: [],
  },
  // — Decimocuarta tanda universal (AXOS-CAD-UNIVERSAL-028): comercio —
  {
    id: "freezer",
    label: "Congelador",
    category: "equipment",
    defaultWidth: 1500,
    defaultHeight: 700,
    layer: "Equipment",
    tags: ["congelador", "freezer", "helados", "minisúper", "minisuper", "carnicería", "carniceria"],
    ports: [],
  },
  {
    id: "coffee-machine",
    label: "Cafetera",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 500,
    layer: "Equipment",
    tags: ["cafetera", "coffee", "café", "cafe", "cafetería", "cafeteria", "barra"],
    ports: [],
  },
  {
    id: "scale",
    label: "Báscula",
    category: "equipment",
    defaultWidth: 500,
    defaultHeight: 500,
    layer: "Equipment",
    tags: ["báscula", "bascula", "scale", "peso", "abarrotes", "carnicería", "carniceria", "fruteria", "frutería"],
    ports: [],
  },
  // — Decimoquinta tanda universal (AXOS-CAD-UNIVERSAL-030): frutería —
  {
    id: "fruit-crate",
    label: "Cajón de fruta",
    category: "equipment",
    defaultWidth: 600,
    defaultHeight: 400,
    layer: "Equipment",
    tags: ["cajón de fruta", "cajon de fruta", "huacal", "guacal", "frutería", "fruteria", "verdulería", "verduleria"],
    ports: [],
  },
  // — Decimosexta tanda universal (AXOS-CAD-UNIVERSAL-032): tortillería —
  {
    id: "tortilla-machine",
    label: "Máquina tortilladora",
    category: "equipment",
    defaultWidth: 1200,
    defaultHeight: 800,
    layer: "Equipment",
    tags: ["máquina tortilladora", "maquina tortilladora", "tortilladora", "tortillería", "tortilleria", "tortillas"],
    ports: [],
  },
  // — Decimoséptima tanda universal (AXOS-CAD-UNIVERSAL-033): papelería —
  {
    id: "copier",
    label: "Copiadora",
    category: "equipment",
    defaultWidth: 700,
    defaultHeight: 600,
    layer: "Equipment",
    tags: ["copiadora", "impresora", "copier", "fotocopiadora", "papelería", "papeleria", "oficina"],
    ports: [],
  },
  // — Decimoctava tanda universal (AXOS-CAD-UNIVERSAL-036): salud —
  {
    id: "exam-table",
    label: "Camilla",
    category: "equipment",
    defaultWidth: 700,
    defaultHeight: 1900,
    layer: "Equipment",
    tags: ["camilla", "exam table", "fisioterapia", "consultorio", "masaje", "spa", "exploración", "exploracion"],
    ports: [],
  },
  // — Decimonovena tanda universal (AXOS-CAD-UNIVERSAL-039): box —
  {
    id: "punching-bag",
    label: "Costal de box",
    category: "equipment",
    defaultWidth: 500,
    defaultHeight: 500,
    layer: "Equipment",
    tags: ["costal", "saco", "box", "boxeo", "punching bag", "gimnasio"],
    ports: [],
  },
  // — Vigésima tanda universal (AXOS-CAD-UNIVERSAL-041): detalles —
  {
    id: "plant-pot",
    label: "Maceta",
    category: "furniture",
    defaultWidth: 400,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["maceta", "planta", "flor", "plant", "decoración", "decoracion"],
    ports: [],
  },
  {
    id: "coat-rack",
    label: "Perchero",
    category: "furniture",
    defaultWidth: 400,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["perchero", "coat rack", "abrigos", "recepción", "recepcion", "entrada"],
    ports: [],
  },
  // — Vigesimoprimera tanda universal (AXOS-CAD-UNIVERSAL-043): mostrador —
  {
    id: "cash-register",
    label: "Caja registradora",
    category: "commerce",
    defaultWidth: 450,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["caja", "registradora", "cobro", "cash register", "punto de venta", "pos"],
    ports: [],
  },
  {
    id: "trash-bin",
    label: "Bote de basura",
    category: "equipment",
    defaultWidth: 400,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["basura", "bote", "cesto", "trash", "residuos", "papelera"],
    ports: [],
  },
  {
    id: "water-dispenser",
    label: "Dispensador de agua",
    category: "equipment",
    defaultWidth: 350,
    defaultHeight: 350,
    layer: "Furniture",
    tags: ["garrafón", "garrafon", "agua", "dispensador", "water", "bebedero"],
    ports: [],
  },
  // — Vigesimosegunda tanda universal (AXOS-CAD-UNIVERSAL-046): eléctricos —
  {
    id: "tv-screen",
    label: "Pantalla / TV",
    category: "equipment",
    defaultWidth: 1200,
    defaultHeight: 150,
    layer: "Furniture",
    tags: ["pantalla", "tv", "televisión", "television", "monitor", "sala"],
    ports: [],
  },
  {
    id: "microwave",
    label: "Microondas",
    category: "equipment",
    defaultWidth: 500,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["microondas", "microwave", "cocina", "comedor de empleados"],
    ports: [],
  },
  {
    id: "pedestal-fan",
    label: "Ventilador de pedestal",
    category: "equipment",
    defaultWidth: 450,
    defaultHeight: 450,
    layer: "Furniture",
    tags: ["ventilador", "fan", "aire", "pedestal"],
    ports: [],
  },
  // — Vigesimotercera tanda universal (AXOS-CAD-UNIVERSAL-049): cocina y barra —
  {
    id: "kitchen-sink",
    label: "Fregadero",
    category: "equipment",
    defaultWidth: 800,
    defaultHeight: 550,
    layer: "Furniture",
    tags: ["fregadero", "tarja", "lavatrastes", "cocina", "sink"],
    ports: [],
  },
  {
    id: "bar-stool",
    label: "Banco alto",
    category: "furniture",
    defaultWidth: 380,
    defaultHeight: 380,
    layer: "Furniture",
    tags: ["banco alto", "banco", "stool", "barra", "taquería", "taqueria", "mostrador"],
    ports: [],
  },
  {
    id: "range-hood",
    label: "Campana de cocina",
    category: "equipment",
    defaultWidth: 900,
    defaultHeight: 500,
    layer: "Furniture",
    tags: ["campana", "extractor", "cocina", "hood", "humo"],
    ports: [],
  },
  // — Vigesimocuarta tanda universal (AXOS-CAD-UNIVERSAL-051): recámara y patio —
  {
    id: "wall-mirror",
    label: "Espejo de pared",
    category: "furniture",
    defaultWidth: 1000,
    defaultHeight: 100,
    layer: "Furniture",
    tags: ["espejo de pared", "espejo", "probador", "gimnasio", "danza", "mirror"],
    ports: [],
  },
  {
    id: "bunk-bed",
    label: "Litera",
    category: "furniture",
    defaultWidth: 2000,
    defaultHeight: 1000,
    layer: "Furniture",
    tags: ["litera", "bunk", "recámara", "recamara", "dormitorio", "hostal"],
    ports: [],
  },
  {
    id: "grill",
    label: "Asador / Parrilla",
    category: "equipment",
    defaultWidth: 800,
    defaultHeight: 500,
    layer: "Furniture",
    tags: ["asador", "parrilla", "grill", "taquería", "taqueria", "jardín", "jardin", "carne asada"],
    ports: [],
  },
  // — Vigesimoquinta tanda universal (AXOS-CAD-UNIVERSAL-054): autolavado y taller —
  {
    id: "vacuum-cleaner",
    label: "Aspiradora",
    category: "equipment",
    defaultWidth: 450,
    defaultHeight: 450,
    layer: "Furniture",
    tags: ["aspiradora", "vacuum", "autolavado", "limpieza"],
    ports: [],
  },
  {
    id: "pressure-washer",
    label: "Hidrolavadora",
    category: "equipment",
    defaultWidth: 500,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["hidrolavadora", "pressure washer", "autolavado", "lavado", "taller"],
    ports: [],
  },
  {
    id: "traffic-cone",
    label: "Cono de tráfico",
    category: "safety",
    defaultWidth: 300,
    defaultHeight: 300,
    layer: "Furniture",
    tags: ["cono", "tráfico", "trafico", "seguridad", "obra", "estacionamiento"],
    ports: [],
  },
  // — Vigesimosexta tanda universal (AXOS-CAD-UNIVERSAL-057): servicios del patio —
  {
    id: "water-tank",
    label: "Tinaco",
    category: "equipment",
    defaultWidth: 1100,
    defaultHeight: 1100,
    layer: "Furniture",
    tags: ["tinaco", "tanque de agua", "water tank", "azotea", "cisterna"],
    ports: [],
  },
  {
    id: "gas-tank",
    label: "Tanque de gas estacionario",
    category: "equipment",
    defaultWidth: 1600,
    defaultHeight: 800,
    layer: "Furniture",
    tags: ["tanque de gas", "gas", "estacionario", "lp", "patio"],
    ports: [],
  },
  {
    id: "water-heater",
    label: "Boiler / Calentador",
    category: "equipment",
    defaultWidth: 500,
    defaultHeight: 500,
    layer: "Furniture",
    tags: ["boiler", "calentador", "agua caliente", "water heater", "patio"],
    ports: [],
  },
  // — Vigesimoséptima tanda universal (AXOS-CAD-UNIVERSAL-060): patio de casa —
  {
    id: "laundry-sink",
    label: "Lavadero",
    category: "equipment",
    defaultWidth: 800,
    defaultHeight: 600,
    layer: "Furniture",
    tags: ["lavadero", "patio de servicio", "ropa", "lavado a mano"],
    ports: [],
  },
  {
    id: "clothesline",
    label: "Tendedero",
    category: "equipment",
    defaultWidth: 2000,
    defaultHeight: 400,
    layer: "Furniture",
    tags: ["tendedero", "ropa", "patio", "clothesline", "secado"],
    ports: [],
  },
  {
    id: "playground",
    label: "Juegos infantiles",
    category: "equipment",
    defaultWidth: 3000,
    defaultHeight: 2500,
    layer: "Furniture",
    tags: ["juegos", "juegos infantiles", "resbaladilla", "columpios", "guardería", "guarderia", "parque"],
    ports: [],
  },
  // — Vigesimoctava tanda universal (AXOS-CAD-UNIVERSAL-061): terraza y asado —
  {
    id: "patio-umbrella",
    label: "Sombrilla de terraza",
    category: "furniture",
    defaultWidth: 2000,
    defaultHeight: 2000,
    layer: "Furniture",
    tags: ["sombrilla", "umbrella", "terraza", "patio", "sombra"],
    ports: [],
  },
  {
    id: "rotisserie",
    label: "Horno rosticero",
    category: "equipment",
    defaultWidth: 900,
    defaultHeight: 700,
    layer: "Furniture",
    tags: ["rosticero", "rosticería", "rosticeria", "pollo rostizado", "rotisserie"],
    ports: [],
  },
  {
    id: "picnic-table",
    label: "Mesa de picnic",
    category: "furniture",
    defaultWidth: 1800,
    defaultHeight: 1500,
    layer: "Furniture",
    tags: ["mesa de picnic", "picnic", "terraza", "jardín", "jardin", "exterior"],
    ports: [],
  },
] as const;

export function getCadSymbol(id: string): CadSymbolDefinition | undefined {
  return CAD_SYMBOL_LIBRARY.find((symbol) => symbol.id === id);
}
export function searchCadSymbols(query: string): CadSymbolDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...CAD_SYMBOL_LIBRARY];
  return CAD_SYMBOL_LIBRARY.filter((symbol) =>
    [symbol.id, symbol.label, symbol.category, ...symbol.tags].some((value) =>
      value.toLowerCase().includes(q),
    ),
  );
}
export function createCadSymbolPlacement(
  symbolId: string,
  x: number,
  y: number,
  id = `${symbolId}-${Date.now()}`,
): CadSymbolPlacement | null {
  const symbol = getCadSymbol(symbolId);
  if (!symbol) return null;
  return {
    id,
    symbolId: symbol.id,
    label: symbol.label,
    x,
    y,
    width: symbol.defaultWidth,
    height: symbol.defaultHeight,
    layer: symbol.layer,
    tags: [...symbol.tags],
  };
}
