/**
 * Plantillas de arranque POR DISCIPLINA — la prueba dibujable de que Valle
 * Design no es sólo arquitectura.
 *
 * El catálogo grande (`templates.ts`) son 145 tipologías de edificio, y eso
 * describía el producto más chico de lo que es: un CAD 2D general dibuja también
 * la pieza que se va a tornear, el unifilar de la casa, el levantamiento del
 * predio y el despiece del mueble. Estas cuatro existen para que eso se vea en
 * la paleta, no sólo en el README.
 *
 * Viven en su propio módulo porque el trinquete de `monolith-budget` sólo deja
 * ENCOGER `templates.ts`, y tiene razón: contenido nuevo va en un archivo nuevo.
 */
import type {
  CadLayoutTemplate,
  CadTemplateAnnotation,
  CadTemplateAsset,
} from "./templates";
import type { CadLayerId } from "./layers";

const asset = (
  ref: string,
  kind: string,
  label: string,
  x: number,
  y: number,
  w: number,
  h: number,
  layer: CadLayerId,
  tags: string[],
  rotation = 0,
): CadTemplateAsset => ({
  ref,
  kind,
  label,
  x,
  y,
  w,
  h,
  layer,
  tags,
  rotation,
});

const note = (
  ref: string,
  text: string,
  x: number,
  y: number,
  layer: CadLayerId,
): CadTemplateAnnotation => ({ ref, type: "text", text, x, y, layer });

/** Las cuatro plantillas de disciplina, en el orden en que se ofrecen. */
export const CAD_DISCIPLINE_TEMPLATES: CadLayoutTemplate[] = [
  {
    id: "pieza-mecanica",
    label: "Pieza mecánica",
    description:
      "Arranque de dibujo mecánico: brida con barreno central y cuatro barrenos de tornillo, vista frontal y corte, con cuadro de tolerancias y acabado.",
    category: "taller",
    baseWidth: 400,
    baseHeight: 260,
    assets: [
      asset(
        "cuerpo",
        "zone",
        "Brida — vista frontal",
        30,
        40,
        160,
        160,
        "layout",
        ["mecanica", "pieza", "vista-frontal", "brida"],
      ),
      asset(
        "barreno-central",
        "zone",
        "Barreno central 40 H7",
        90,
        100,
        40,
        40,
        "layout",
        ["mecanica", "barreno", "tolerancia", "h7"],
      ),
      asset(
        "barreno-1",
        "zone",
        "Barreno M8 (1 de 4)",
        55,
        65,
        12,
        12,
        "layout",
        ["mecanica", "barreno", "tornillo", "m8"],
      ),
      asset(
        "barreno-2",
        "zone",
        "Barreno M8 (2 de 4)",
        153,
        65,
        12,
        12,
        "layout",
        ["mecanica", "barreno", "tornillo", "m8"],
      ),
      asset(
        "barreno-3",
        "zone",
        "Barreno M8 (3 de 4)",
        55,
        163,
        12,
        12,
        "layout",
        ["mecanica", "barreno", "tornillo", "m8"],
      ),
      asset(
        "barreno-4",
        "zone",
        "Barreno M8 (4 de 4)",
        153,
        163,
        12,
        12,
        "layout",
        ["mecanica", "barreno", "tornillo", "m8"],
      ),
      asset("corte", "zone", "Corte A-A", 230, 40, 140, 160, "layout", [
        "mecanica",
        "corte",
        "seccion",
        "vista",
      ]),
      asset(
        "eje-corte",
        "path",
        "Eje de corte A-A",
        30,
        118,
        160,
        4,
        "measurements",
        ["mecanica", "eje", "corte", "referencia"],
      ),
      asset(
        "cuadro",
        "zone",
        "Cuadro de tolerancias y acabado",
        30,
        215,
        340,
        30,
        "measurements",
        ["mecanica", "tolerancias", "acabado", "cuadro"],
      ),
    ],
    annotations: [
      note(
        "titulo",
        "PIEZA MECANICA — brida, escala 1:1, cotas en mm",
        30,
        25,
        "measurements",
      ),
      note(
        "tol",
        "Barreno central 40 H7 · barrenos M8 a 4 x 90 grados · Ra 3.2 · acero 1018",
        34,
        232,
        "measurements",
      ),
      note("corte-nota", "CORTE A-A", 235, 30, "measurements"),
    ],
    connectors: [],
  },
  {
    id: "diagrama-unifilar",
    label: "Diagrama unifilar",
    description:
      "Arranque de dibujo eléctrico: acometida, medidor, interruptor principal y tablero con cuatro circuitos derivados, con cuadro de cargas.",
    category: "instalaciones",
    baseWidth: 3200,
    baseHeight: 2400,
    assets: [
      asset(
        "acometida",
        "power_panel",
        "Acometida",
        200,
        200,
        300,
        200,
        "utilities",
        ["electrico", "acometida", "unifilar"],
      ),
      asset(
        "medidor",
        "power_panel",
        "Medidor",
        700,
        200,
        260,
        200,
        "utilities",
        ["electrico", "medidor", "unifilar"],
      ),
      asset(
        "principal",
        "power_panel",
        "Interruptor principal 2x60 A",
        1160,
        200,
        340,
        200,
        "utilities",
        ["electrico", "interruptor", "principal", "unifilar"],
      ),
      asset(
        "tablero",
        "cabinet",
        "Tablero de distribución",
        1700,
        160,
        420,
        280,
        "utilities",
        ["electrico", "tablero", "distribucion", "unifilar"],
      ),
      asset(
        "c1",
        "network_drop",
        "C1 — alumbrado 1x15 A",
        600,
        700,
        700,
        180,
        "utilities",
        ["electrico", "circuito", "alumbrado"],
      ),
      asset(
        "c2",
        "network_drop",
        "C2 — contactos 1x20 A",
        600,
        1000,
        700,
        180,
        "utilities",
        ["electrico", "circuito", "contactos"],
      ),
      asset(
        "c3",
        "network_drop",
        "C3 — cocina 1x20 A",
        600,
        1300,
        700,
        180,
        "utilities",
        ["electrico", "circuito", "cocina"],
      ),
      asset(
        "c4",
        "network_drop",
        "C4 — aire acondicionado 2x30 A",
        600,
        1600,
        700,
        180,
        "utilities",
        ["electrico", "circuito", "clima"],
      ),
      asset(
        "tierra",
        "column",
        "Electrodo de tierra física",
        2400,
        1600,
        200,
        200,
        "utilities",
        ["electrico", "tierra", "puesta-a-tierra"],
      ),
      asset(
        "cuadro-cargas",
        "zone",
        "Cuadro de cargas",
        1600,
        700,
        1400,
        900,
        "measurements",
        ["electrico", "cuadro", "cargas", "calculo"],
      ),
    ],
    annotations: [
      note(
        "titulo",
        "DIAGRAMA UNIFILAR — vivienda unifamiliar",
        200,
        120,
        "measurements",
      ),
      note(
        "nota-norma",
        "Calibres y protecciones según NOM-001-SEDE vigente",
        1620,
        760,
        "measurements",
      ),
      note(
        "nota-tierra",
        "Resistencia de puesta a tierra menor o igual a 25 ohm",
        2280,
        1880,
        "measurements",
      ),
    ],
    connectors: [
      { fromRef: "acometida", toRef: "medidor", kind: "flow" },
      { fromRef: "medidor", toRef: "principal", kind: "flow" },
      { fromRef: "principal", toRef: "tablero", kind: "flow" },
      { fromRef: "tablero", toRef: "c1", kind: "flow" },
      { fromRef: "tablero", toRef: "c2", kind: "flow" },
      { fromRef: "tablero", toRef: "c3", kind: "flow" },
      { fromRef: "tablero", toRef: "c4", kind: "flow" },
      { fromRef: "tablero", toRef: "tierra", kind: "flow" },
    ],
  },
  {
    id: "levantamiento-predio",
    label: "Levantamiento de predio",
    description:
      "Arranque topográfico: polígono de cuatro lados con vértices, colindancias, banqueta y calle, con cuadro de construcción listo para llenar.",
    category: "civil",
    baseWidth: 40000,
    baseHeight: 30000,
    assets: [
      asset(
        "predio",
        "zone",
        "Polígono del predio",
        6000,
        6000,
        24000,
        16000,
        "layout",
        ["topografia", "predio", "poligono", "levantamiento"],
      ),
      asset("v1", "column", "Vértice 1", 5850, 5850, 300, 300, "measurements", [
        "topografia",
        "vertice",
        "mojonera",
      ]),
      asset(
        "v2",
        "column",
        "Vértice 2",
        29850,
        5850,
        300,
        300,
        "measurements",
        ["topografia", "vertice", "mojonera"],
      ),
      asset(
        "v3",
        "column",
        "Vértice 3",
        29850,
        21850,
        300,
        300,
        "measurements",
        ["topografia", "vertice", "mojonera"],
      ),
      asset(
        "v4",
        "column",
        "Vértice 4",
        5850,
        21850,
        300,
        300,
        "measurements",
        ["topografia", "vertice", "mojonera"],
      ),
      asset("banqueta", "path", "Banqueta", 6000, 3600, 24000, 1800, "aisles", [
        "topografia",
        "banqueta",
        "circulation",
        "via",
      ]),
      asset("calle", "path", "Calle", 3000, 1400, 34000, 2000, "aisles", [
        "topografia",
        "calle",
        "via",
        "circulation",
      ]),
      asset(
        "colindancia-n",
        "wall",
        "Colindancia norte",
        6000,
        22000,
        24000,
        200,
        "architecture",
        ["topografia", "colindancia", "norte"],
      ),
      asset(
        "colindancia-e",
        "wall",
        "Colindancia oriente",
        30000,
        6000,
        200,
        16000,
        "architecture",
        ["topografia", "colindancia", "oriente"],
      ),
      asset(
        "cuadro-construccion",
        "zone",
        "Cuadro de construcción",
        6000,
        24500,
        18000,
        4200,
        "measurements",
        ["topografia", "cuadro", "construccion", "rumbos"],
      ),
    ],
    annotations: [
      note(
        "titulo",
        "LEVANTAMIENTO TOPOGRAFICO — escala 1:200, cotas en metros",
        6000,
        29200,
        "measurements",
      ),
      note(
        "cuadro",
        "EST | P.V. | RUMBO | DISTANCIA | V | X | Y — llenar con la libreta de campo",
        6200,
        26800,
        "measurements",
      ),
      note(
        "superficie",
        "Superficie: 384.00 m2 · Perímetro: 80.00 m",
        6200,
        25200,
        "measurements",
      ),
      note("norte", "NORTE", 33000, 20000, "measurements"),
    ],
    connectors: [],
  },
  {
    id: "despiece-carpinteria",
    label: "Despiece de carpintería",
    description:
      "Arranque de mobiliario: librero de tres entrepaños despiezado en costados, entrepaños, respaldo y zócalo, con lista de corte.",
    category: "taller",
    baseWidth: 2600,
    baseHeight: 1800,
    assets: [
      asset(
        "costado-izq",
        "zone",
        "Costado izquierdo 1800x350x18",
        120,
        200,
        180,
        900,
        "layout",
        ["carpinteria", "despiece", "costado", "mdf"],
      ),
      asset(
        "costado-der",
        "zone",
        "Costado derecho 1800x350x18",
        360,
        200,
        180,
        900,
        "layout",
        ["carpinteria", "despiece", "costado", "mdf"],
      ),
      asset(
        "entrepano-1",
        "zone",
        "Entrepaño 1 — 764x350x18",
        620,
        200,
        380,
        180,
        "layout",
        ["carpinteria", "despiece", "entrepano"],
      ),
      asset(
        "entrepano-2",
        "zone",
        "Entrepaño 2 — 764x350x18",
        620,
        440,
        380,
        180,
        "layout",
        ["carpinteria", "despiece", "entrepano"],
      ),
      asset(
        "entrepano-3",
        "zone",
        "Entrepaño 3 — 764x350x18",
        620,
        680,
        380,
        180,
        "layout",
        ["carpinteria", "despiece", "entrepano"],
      ),
      asset(
        "respaldo",
        "zone",
        "Respaldo — 1780x780x6",
        1080,
        200,
        420,
        660,
        "layout",
        ["carpinteria", "despiece", "respaldo", "triplay"],
      ),
      asset(
        "zocalo",
        "zone",
        "Zócalo — 764x80x18",
        620,
        920,
        380,
        90,
        "layout",
        ["carpinteria", "despiece", "zocalo"],
      ),
      asset(
        "armado",
        "zone",
        "Vista de armado",
        1600,
        200,
        850,
        900,
        "layout",
        ["carpinteria", "armado", "vista", "conjunto"],
      ),
      asset(
        "lista-corte",
        "zone",
        "Lista de corte",
        120,
        1180,
        2330,
        480,
        "measurements",
        ["carpinteria", "lista", "corte", "optimizacion"],
      ),
    ],
    annotations: [
      note(
        "titulo",
        "DESPIECE DE CARPINTERIA — librero de 3 entrepaños, cotas en mm",
        120,
        130,
        "measurements",
      ),
      note(
        "lista",
        "MDF 18 mm: 2 costados + 3 entrepaños + 1 zócalo · Triplay 6 mm: 1 respaldo · Canto PVC 0.45 mm",
        160,
        1300,
        "measurements",
      ),
      note(
        "nota-armado",
        "Uniones: taquete de 8 mm + tornillo confirmat 7x50 · perforación cada 32 mm",
        160,
        1480,
        "measurements",
      ),
    ],
    connectors: [],
  },
];
